### ISSUE TITLE
Client Hint for CPU "bitness"

### ISSUE THREAD

**Issue by yoavweiss** [WICG/ua-client-hints#105]
There may be use-cases in which detailed CPU architectures is needed (e.g. download of highly-optimized binary executables).
It would be good to keep the current `architecture`/`Sec-CH-UA-Arch` relatively low-entropy (for the common case), and potentially expose more detailed info only to sites that opt-in to that specifically.

**Comment by othermaciej** [comment]
I don't think this is a good idea; it's quite a bit of extra entropy. Is this exposed in any current User-agent strings?

**Comment by yoavweiss** [comment]
> I don't think this is a good idea

I'm not 100% sure it is either, therefore I marked it as "enhancement", that may be part of a future iteration. 

The motivation here: As part of https://github.com/WICG/ua-client-hints/pull/106 we significantly reduce the entropy currently exposed (at least in Chromium, at least in some platforms), under the assumption that it's sufficient for binary downloads.

The idea is that *if* legitimate use-cases arise that actually need that extra information, we'd be able to provide that information without forcing the more common use cases to touch that entropy.

**Comment by bslassey** [comment]
@othermaciej this is related to https://github.com/WICG/ua-client-hints/pull/106#discussion_r421971178 where you said that the 32/64bit distinction is important. Entropy-wise, having a single hint that has arm32, arm64, x86 and x86_64 versus two hints with arm, x86 and 32, 64 values is the same. 

Practically, I see some benefits from separating the two. First, it is forward compatible in that as the architectures have expanded (i.e. when 32 bit and 64 bit chips were introduced) existing binaries were backward compatible (so 16bit binaries ran on 32 bit chips and 32 bit binaries ran on 64 bit chips). In the future when we have 128 bit chips, I would hate to see a world where the x86_128 or arm128 tokens caused sites serving 64 bit binaries to error out. 

On a similar token, right now if I am a site hosting 32 bit x86 or 32 bit arm binaries, I don't particularly care about the distinction of 32 and 64 bit when user is trying to download them.

**Comment by othermaciej** [comment]
Not all 64-bit operating systems for arm or x86 are able to run 32-bit binaries. (For example, the latest versions of macOS and iOS are strictly 64-bit only; and there's apparently Linux distributions that have 64-bit only userland). But perhaps this is not the common case.

I did not initially get that this was only meant to express 64-bit vs 32-bit. I imagined "detailed CPU architecture" would mean a specific processor or processor generation, e.g. `Intel Core i7 9700k` or `Qualcomm Snapdragon 410` or `Apple A13 Bionic`. 

A hint for just 32-bit vs 64-bit seems ok, though I'm not sure there is much win to separating x86/arm/blank from 32/64/blank.

(For Safari on Apple platforms, we'll probably always leave these blank, or pick one fixed value for all mobile and another for all desktop, even if these have to be fake on some devices.)

**Comment by othermaciej** [comment]
(Or perhaps you could imagine something short of exact CPU model but still more than the broad architecture class. Within 64-bit ARM, the original version is `ARMv8-A` and `ARMv8.1-A` through `ARMv8.6-A` versions of the ISA each add new instructions. This is what I assumed from "highly optimized".)

**Comment by othermaciej** [comment]
Can we change the title of this issue to make clear that it's only about "bitness" for related 32-bit and 64-bit CPU architectures, and not about more specific instruction set architecture versions like `ARMv8.6-A`, or exact CPU models like `Qualcomm Snapdragon 410`?

**Comment by yoavweiss** [comment]
Changed.

We may still look into exposing more specific instruction set in the future, but I agree that if we'd do something like that, it'd probably be yet another hint, and it's better to focus this issue on the clearer use case.

**Comment by bslassey** [comment]
UA-CH-CPU-Bitwidth?

**Comment by tresf** [comment]
> Is this exposed in any current User-agent strings?

* ✅ Windows seems to send it (Edgium):

    ```
    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
    Chrome/81.0.4044.138 Safari/537.36 Edg/81.0.416.77
                                  ^---   ^---
    ```
* 🚫 MacOS does NOT send it: (Safari):
    ```
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
    ```
    (you probably know this already since you develop WebKit for Apple)

* ✅ Ubuntu does send it (Firefox):
    ```
    User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
                                                ^---
    ```

**Comment by othermaciej** [comment]
On macOS we chose to use "Intel" to represent both flavors of the x86 CPU architecture and have never exposed this distinction to the web. iPads (by default) and iPhones (when using "Request Desktop Site") both also claim to be "Intel". I think if we implement UA client hints, we'd likely not expose the CPU architecture or fitness on any Apple platform.

**Comment by tresf** [comment]
> we'd likely not expose the CPU architecture or fitness on any Apple platform.

That's Apple's prerogative, but as ARM slowly invades the desktop, this can remove information for ISVs providing downloads.  At time of writing this, Windows and Linux both provide it.  My understanding of the client-hints was to allow this type of information when requested (as opposed to User-Agent which doesn't give the end-user an option to opt-out).  I'd expect more information through sanctioned channels and for this reason, I'd expect browsers to make an upfront attempt to remain the same.

That said, fro an ISV's perspective, Safari poses other technical issues already.  Furthemore, Apple's philosophy on mixed architecture (if such a thing ever occurs) has always been to offer up a "Universal" packager for all to remove any selection-burden from the end-user at the expense of download size.  Ultimately, downstream's always at the mercy of the decisions of upstream, but if a standard is accepted, it'd be stellar to have Safari on board with that.

**Comment by othermaciej** [comment]
This incubation spec (not yet a standard) allows omitting this info, and we’re on board with this.

You’re right that Apple’s recommendation across CPU arch transitions is generally universal binaries (or else an emulator, as was done for PPC —> Intel.

**Comment by tresf** [comment]
As a downstream implementer, I'm still unsure how to handle this.  @othermaciej although I respect the decision to keep this info private, for those that do provide it, the spec seems to still require definition, no?  For now, I think I'll just keep it as `x86_64`, or whatever I'm setting in the `User-Agent` string but I'd be happy to use a more formal technique for future proofing.

**Comment by othermaciej** [comment]
Refer to the spec and its editors for what's allowed in this field. I think the intent is that the main CPU field will only be `arm`, `x86` or blank, and this field (not yet added to the spec) will distinguish 32-bit vs 64-bit.

**Comment by tresf** [comment]
> Refer to the spec and its editors for what's allowed in this field.

The readme says ARM64, the PR has unanswered questions.  Worse, it leaves no room for odd architectures like ppc, so I find this to be dismissive.  Regardless, I'll use `x86_64`.  I'm not looking to win an argument, just preparing for the future.

**Comment by tresf** [comment]
Rephrasing.... 

> Refer to the spec for what's allowed in this field.

Hmm...  well, the readme says `ARM64`, and the PR says `arm` but still has unanswered questions, so "refer to the spec" seems a bit premature.

>  Refer to [the spec's] editors for what's allowed in this field.

Is this not the correct forum?

**Comment by yoavweiss** [comment]
> Hmm... well, the readme says `ARM64`, and the PR says `arm` but still has unanswered questions, so "refer to the spec" seems a bit premature.

Thanks for pointing out that contradiction. https://github.com/WICG/ua-client-hints/pull/112 fixes the README.
