### ISSUE TITLE
API to expose full version (was: An API to expose only the major version)

### ISSUE THREAD

**Issue by yoavweiss** [WICG/ua-client-hints#11]
The JS API in the proposal only includes a single `version` property, which means there's no "free" way to access the major version information without touching any extra bits. There probably should be.

**Comment by dasa** [comment]
Could be allowed in insecure contexts as well?

**Comment by gdh1995** [comment]
I like this idea. And I want that "`brand`" and "`major version`" can be accessible without waiting for a `Promise`. For example, if it's not async, then a first `<script>` can recognize most of browser bugs and lacked features, and then registers some necessary polyfills globally.

Here's a real use case: my web extension, Vimium C, now does such checks immediately when its content scripts get executed:
* it registers a listener for `DOMActivate` on Chrome, while `mouse` on Firefox
  * if `brand` is in a "promise", then it will have to register both listeners when initing (in case a page may suppresss "click" events), and then remove an unused one when the promise gets resolved (to release memory)
* when injecting `<script>`, it detects the major verision of Chrome, to avoid bugs / different behavior in different versions
  * _this injection has to run before all other code_: the injected code is to hook `addEventListener`, while some libraries like Zone.js and Lodash caches `addEventListener` during initing and then it's too danger to hook this function after host scripts get inited.
  * if `major version` is in a "promise", then it has to run some extra checks to collect features of current Chrome and avoid potential crashes
* on Chrome 69, it still runs web extensions on a page whose CSP includes `sandbox`, but:
  * `requestAnimationFrame` and `requestIdleCallback` only fails silently
  * if `major version` is in a "promise", then I have to wrap all invocations in promises
* **there may be some other bugs in the future**, which means a promise of `major version` will cause some work-around to be unreliable or even impossible.

**Comment by yoavweiss** [comment]
> I like this idea. And I want that "`brand`" and "`major version`" can be accessible without waiting for a `Promise`.

@gdh1995 That's indeed where we ended up. See https://github.com/WICG/ua-client-hints/pull/48

Regarding the OP, since `brand` now exposes brand and major version, we should create another `getVersion` that returns a Promise for the full version (and a separate CH for that as well).
