### ISSUE TITLE
Client hint for "color-scheme"

### ISSUE THREAD

**Issue by sangwoo108** [WICG/ua-client-hints#113]
Hi. I wonder if we can add an additional client hint for "color-scheme", which would be an alternative for ["prefers-color-scheme" media query in CSS](https://developer.mozilla.org/ko/docs/Web/CSS/@media/prefers-color-scheme).

If a request gives a server the information, then the server can provide  styleshees, images optimized based on the client's preference. I guess this might save the size of stylesheets and others too.

**Comment by yoavweiss** [comment]
I'd be supportive of such a feature, but it doesn't seem directly related to user agent information, so I don't think it should be discussed here.

The right place to discuss it is in https://github.com/w3c/csswg-drafts/issues/4162

**Comment by sangwoo108** [comment]
Aha, it should be HTTP client hint. Thanks for the redirection!
