### ISSUE TITLE
Usage share analytics + GREASE + white lies for compatibility

### ISSUE THREAD

**Issue by quasicomputational** [WICG/ua-client-hints#115]
The GREASE in the brands list effectively means that, looking at individual brands inside it, a browser recogniser must fail open and ignore anything it doesn't understand.

In the context of actually delivering a page and making it work, this is desirable: it promotes resillience and ought to gracefully degrade.

However, it's more troublesome when trying to use `Sec-CH-UA` for counting browser usage shares.

Consider a minority browser based on Chromium. Because it's a minority but likely quite Chrome-compatible, it's very possible that it'll claim to be Chrome in `Sec-CH-UA`, as well as its true name, relying on the GREASEing to keep the true name's presence from causing trouble as far as displaying pages works. So far, so good. Once the minority browser starts showing up in analytics, Web developers will start acknowledging its existence, and gradually the need to lie will fade away, right?

Except, how should usage share analytics work here? How can the minority browser's true name be distinguished from Chrome's GREASE? Because unknown brand names have to be ignored, the minority browser just gets bucketted as 'Chrome', meaning that the compatibility-versus-truthfulness dilemma persists - it doesn't show up in analytics, therefore no-one bothers to add its brand name to their recognisers.

The effect here will likely be that Chrome winds up with an inflated market share, only reinforcing its hegemony, and minority browsers have another impediment put in front of them. This is less than ideal for the health of the Web.

One thing to do here would be to recognise that analytics and page-display need different things from a browser recogniser. In the latter, just finding a brand that you recognise in the list + GREASE enforcing failing open is plenty good enough; failing open is definitely the thing to do, because graceful degradation. In the former, you do want to identify the exact browser and fail closed if you can't; analytics breaking doesn't break the page, so this is OK. How can this be made to work with GREASE?

The considerations around caching already mean that the spec recommends fixing the GREASE per browser version, and I think that that's probably enough to work with here: analytics could look at the set of brands & versions and match it as a whole against a known list sent by each browser version. It'd mean that the recogniser used for analytics would need to be updated for every new browser version; but, as noted, analytics breaking doesn't break the site, so this is palatable.

So, my concrete suggestion here is that no major change is needed here, but section 5.2 ('GREASE-like UA strings') could do with mentioning analytics as another reason to minimise within-version variance, parallel to the `SHOULD` about caching, and then some discussion in the explainer about analytics wanting to fail closed and looking at `Sec-CH-UA` as a unit while warning about the ecological pitfalls of trying to inspect it too deeply.

**Comment by yoavweiss** [comment]
That sounds reasonable.

**Comment by miketaylr** [comment]
> So, my concrete suggestion here is that no major change is needed here, but section 5.2 ('GREASE-like UA strings') could do with mentioning analytics as another reason to minimise within-version variance, parallel to the `SHOULD` about caching, and then some discussion in the explainer about analytics wanting to fail closed and looking at `Sec-CH-UA` as a unit while warning about the ecological pitfalls of trying to inspect it too deeply.

I understand the suggestion to mention analytics related to version variance, but I'm not sure what the recommended discussion parts for the explainer are. @quasicomputational would you like to write a PR and we can work on it together?

**Comment by quasicomputational** [comment]
The key idea I want to get across is 'by design, if you look at individual entries in the brands list, you can't tell a minority browser's true name apart from Chrome's GREASE; since that's exactly what you want to do in analytics, you should look at the brands list as a unit'. I'll put together a first draft of a PR and we'll see if that can't be expressed in some clear way.

**Comment by miketaylr** [comment]
Thanks!

**Comment by mckingho** [comment]
Is it correct that analytics should use a mapping of `Sec-CH-UA` list to browser, in order to identify browsers?
If so, how can this prevent UA-based allowing/blocking site from using same approach as analytics?

**Comment by Sora2455** [comment]
> Is it correct that analytics should use a mapping of Sec-CH-UA list to browser, in order to identify browsers?
No, because GREASE makes sure that the Sec-CH-UA keeps changing to semi-random values. Some of them are shared between multiple browsers (Chrome, for example, sometimes identifies itself just as a Chromium browser and not which one. If more than one browser do that...)
