### ISSUE TITLE
Spec doesn't define all Accept-CH tokens?

### ISSUE THREAD

**Issue by ericlaw1979** [WICG/ua-client-hints#116]
https://wicg.github.io/ua-client-hints/ does not seem to  clearly explain what you need to put in Accept-CH for the browser to send the Sec-CH-UA-Arch request header, for example.

**Comment by ericlaw1979** [comment]
e.g. https://browserleaks.com/client-hints gets it wrong, sending

`Accept-CH: viewport-width, dpr, device-memory, rtt, downlink, ect, ua, platform, arch, model, mobile`

**Comment by amtunlimited** [comment]
I will point out that they are defined in the [Client Hint Infrastructure](https://wicg.github.io/client-hints-infrastructure/#client-hints-token-definition), but it seems reasonable to put the in here somewhere too.
