### ISSUE TITLE
CPU Architectures now limited to x86 and ARM

### ISSUE THREAD

**Issue by EraYaN** [WICG/ua-client-hints#118]
Would it be feasible to add the other "mainstream" workstation CPU architectures? Think POWER and RISC-V? It reads like an exhaustive listing right now, and it feels wrong to not have some form of completeness. People doe manufacture POWER workstations and RISC-V seems to have a couple of experimental ones. Technically there is also SPARC with workstations but that seems to have mostly died off.

Now some of these have the issue of being LE and BE sometimes, so that might need to be added to the bitness 16/32/64/n for example so proper binaries could be served. This might also be useful for headless servers when asking for their own architecture/mirrors/repository.

It might be enough to just allow arbitrary names or based on some other source (for example gcc/llvm arch name or something like it.)

**Comment by yoavweiss** [comment]
I don't think there's high likelihood that these CPU architectures are going to require the [binary download](https://github.com/WICG/ua-client-hints#download-of-appropriate-binary-executables) use case. Are there popular download sites that provide binaries for these architectures?

Exposing those values seems like something that would make those users highly targetable, and I'm not sure I see the benefit in doing so.

**Comment by EraYaN** [comment]
I am not sure if I'm going to make the most sense, but I'm going to try below.

I suppose the biggest use case is in package repositories/open source downloads for now, until usage patterns change and someone actually gets a good RISC-V SoC out into a phone. But I suppose the spec could talk about some "other" or unspecified platform. Since now it reads to me as if these two are the only two in the world. It sort of irks me that it's an incomplete list without a catch all. And besides who knows what the architecture landscape looks like in say 5 years. God knows they are all trying. Maybe not listing these explicitly but providing some form of "other" or unspecified explicitly in the spec would work, although it might diminish the usefulness if then every UA decides to always put other for privacy concerns. Or even guidance on what name to use for new and upcoming architectures, like defining a source of potential strings (GCC, LLVM etc).

I might have misunderstood the point of the header, but right now a lot of this is solved by just the content of the HTTP requests to tell the server what architecture is expected, but it seemed like a nice header to use for just that just like how you can use headers like Accept-Language to negotiate the correct language of the shipped file instead of lifting that information one level "higher" in the protocol stack.

And since they are not as popular there aren't really any big download sites that do provide downloads. Except for any linux software repository website, which are quite large, but of course linux is fairly niche.

The biggest issue right now that I seen in the wild is that people don't know whenever or not they should download armhf vs arm and if the hints could just help us show the correct one at the top for example. I suppose as soon as some company puts another architecture in the hand of consumers this only gets worse, and we could just ask the client what it's running on.

In the end for browsers this might work as a high entropy version of the architecture in the API (so also including things like endianness, bitness and for example arm version, basically everything needed to compile for the target) but for headless scripts/clients without javascript etc, this isn't really sufficient or workable.

**Comment by yoavweiss** [comment]
Nothing prevents this list from being expanded in the future, and it is not trying to be a comprehensive list of CPU architectures. These are just values that we deem today to be interesting to send in order to tackle the binary download use case, on platforms and architectures where it makes sense.

**Comment by EraYaN** [comment]
I doubt that the list will ever be expanded for the less used architectures, power seems to be mostly academics and big-data enterprise right now and riscv is all in raspberry pi style computers, hence why other values (non-defined) or something similar might be useful in the specification. So those platforms do not need to just break away from the standard, cause then it might just end up being a convention instead of it being written down in a standard document.

If this is not something you are interested in this can be closed.

**Comment by yoavweiss** [comment]
For less used architectures, we explicitly don't want to include them in the potential values, as this would increase the API's entropy for those users, without providing meaningful user benefits (as download sites are not likely to offer binary downloads for them).

"Other" or "unknown" values are not materially different than an empty value.
