### ISSUE TITLE
Remove migration / deprecation

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#125]
The document is a technical proposal for a method that can be run in parallel with an existing de facto standard of interoperability. The two are not directly related and the reference to deprecation and migration should be removed.

The approach to parallel running, gaining feedback, and governing any eventual change to the existing de facto standard of interoperability is not within the scope of the WICG. 

A new W3C working group with a charter to plan this migration would comply with established norms for deploying a major enhancement to 4,500,000,000 people. This commentator would be happy to work with the authors to produce such a group charter. Such a group charter would involve the wide stakeholder consultation needed.

See [this pull request]( https://github.com/WICG/ua-client-hints/pull/124) which incorporates experiment feedback and review from interested users and other stakeholders for proposed text changes.

**Comment by yoavweiss** [comment]
> the reference to deprecation and migration should be removed

The mention of [User-Agent header deprecation](https://wicg.github.io/ua-client-hints/#user-agent) is in reference of the Client Hints Internet-Draft that indicates that [User agents SHOULD remove equivalent passive information exposure](https://tools.ietf.org/html/draft-ietf-httpbis-client-hints-15#page-6:~:text=.%20%20User%20agents,passively.).

**Comment by jwrosewell** [comment]
The Client Hints Internet-Draft is a document with common authorship to this one and is an experiment that will expire on 4th January 2021. Both documents have been advanced in parallel in the forums of W3C and IETF.

This issue applies equally to both documents. Unfortunately, due to the number of related documents and complexity associated with this proposal, and a lack of skilled people’s time relative to Google, this similar issue was not raised during the IETF review process. We intend to raise this once we can dedicate more people to work on this problem and prior to the end of the experiment.

Perhaps @mnot could comment?

**Comment by miketaylr** [comment]
> The Client Hints Internet-Draft is a document with common authorship to this one and is an experiment that will expire on 4th January 2021.

FWIW https://datatracker.ietf.org/doc/html/rfc8942#section-4.1 progressed from draft status to RFC.

As mentioned in https://github.com/WICG/ua-client-hints/pull/174#issuecomment-918193227, [and elsewhere](https://github.com/WICG/ua-client-hints/issues/176#issuecomment-788333382), when there is multi-implementer support and when we have the bulk of the meaningful spec issues fixed, we will propose moving this work from WICG to an appropriate W3C working group.
