### ISSUE TITLE
List dependencies, status and intentions

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#126]
The document should clearly list the dependent specifications and the version that it is dependent on. Where the dependency is not a candidate recommendation or an otherwise ratified specification under formal version control this should be clearly marked and the authors intentions in relation to these dependencies explained.

For example; “ratification by IETF of HTTP Client Hints must be achieved before this proposal will be progressed beyond WICG”

This should also include a reference to the Feature Policy referenced in the document.

See [this pull request]( https://github.com/WICG/ua-client-hints/pull/124) which incorporates experiment feedback and review from interested users and other stakeholders for proposed text changes.

**Comment by yoavweiss** [comment]
The specification already contains a [references](https://wicg.github.io/ua-client-hints/#references) section, but it seems like Client-Hints Infrastructure is missing from it. I'll add it there.

**Comment by jwrosewell** [comment]
Needs to be reopened as the intentions associated with the dependency was not addressed.

**Comment by miketaylr** [comment]
https://github.com/WICG/ua-client-hints/pull/195 which just landed is also related.
