### ISSUE TITLE
Incomplete use cases

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#128]
The use cases need expanding and further consultation.

I hope we can agree that wide consultation is needed when proposing a change to the web that demonstrability impacts the vast majority of implementors and the people and societies that rely on their services. The proposal requires far greater external review and impact assessment before it is used in practice.

See [this pull request]( https://github.com/WICG/ua-client-hints/pull/124) which incorporates experiment feedback and review from interested users and other stakeholders for proposed text changes.

**Comment by yoavweiss** [comment]
Any specific missing use-cases?

**Comment by jwrosewell** [comment]
An expanded set have been listed in the PR referenced.

I suggest we use the TPAC breakout session today to determine how to obtain a more exhaustive list of use cases and confirm the “complete set”.

For example in the field of image optimization; Akamai, CDN77, Cloudflare, CloudImage, Cloudinary , Fastly, Imgix, ImageKit, and ScientiaMobile are all experts in this field.

Similarly, in the field of fraud prevention, Anura, Impact, Imperium, Jscrambler, Pixelate, Integral Ad Science, Oracle (Moat), Sift among many others are all stakeholders in this proposal.

These companies can reasonably be expected to represent the views of their customers and users as my organisation has done via this pull request.

**Comment by yoavweiss** [comment]
Looking at https://github.com/WICG/ua-client-hints/pull/124/files#diff-5e793325cd2bfc452e268a4aa2f02b4024dd9584bd1db3c2595f61f1ecf7b985R197, it seems like:
* (5) seems to map well to https://github.com/WICG/ua-client-hints#low-powered-devices
* (6) maps to https://github.com/WICG/ua-client-hints#marketshare-analytics
* (7) extends on the above a bit, but doesn't seem inherently different
* (8) & (9) are covered by https://github.com/WICG/ua-client-hints#spam-filtering-and-bot-detection

Seems like we could resolve this by integrating the use-cases from the explainer into the spec.

**Comment by jwrosewell** [comment]
I suggest that we start the meeting later with a review of the use cases and ensure we understand each one and the mitigations.

**Comment by miketaylr** [comment]
> Seems like we could resolve this by integrating the use-cases from the explainer into the spec.

That happened in https://github.com/WICG/ua-client-hints/issues/148, so let's close here.
