### ISSUE TITLE
Alternatives require greater consideration

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#129]
There is a problem acknowledged in the AC forum [https://lists.w3.org/Archives/Member/w3c-ac-forum/2020JulSep/0133.html] associated with the name incubation in the W3C Process. It implies the proposer desires the proposal to be successful and sends the wrong message to stakeholders unfamiliar with the W3C Process. The word “experiment” is often used as a synonym for “incubation”. This is a failing in the process which is better described by “experimentation”.  The process of experimentation yields information from which to then form a conclusion. It is open to the possibility of a failure path.

As an experimental proposal alternative solutions need to be considered and dismissed to justify why this experiment is needed over other alternatives. What work has been done in this area? How did those experiments progress?

One such alternative could include providing advice to implementors to gradually restructure the conventions associated with the existing User-Agent header field value to address one of the problems identified concerning ease of data consumption.

See [this pull request]( https://github.com/WICG/ua-client-hints/pull/124) which incorporates experiment feedback and review from interested users and other stakeholders for proposed text changes.

**Comment by yoavweiss** [comment]
> There is a problem acknowledged in the AC forum [https://lists.w3.org/Archives/Member/w3c-ac-forum/2020JulSep/0133.html]

This seems to point at your own email. Did you mean to post a different, non-self-referencing link?

Otherwise, can I sum up your issue above as "A 'Considered Alternatives' section is missing from the explainer"?

**Comment by jwrosewell** [comment]
Yes. The document should contain a section explaining the alternatives and why they were rejected.
