### ISSUE TITLE
Extedning the spec

### ISSUE THREAD

**Issue by twirl** [WICG/ua-client-hints#13]
Hey everyone.

I've been developing rather sophisticated web-apps over years, and I'd be happy to share edge cases not covered by current spec:

1. Browser base. There are plenty of custom browsers which are either Chromium-based or Firefox-based (IceWeasel, for example). Providing  this piece of data would significantly improve web experience, since web developers can provide fallbacks to basic behavior when browser name is unknown;

2. Engine name and its version. There are plenty of bugs depending rather on engine version than browser itself, especially when custom browser use only layout engine (i.e. Webkit), not entire browser build.

3. `Mobile` flag seems too narrow. It mostly needed for guessing:
  * whether or not user uses mouse/pen (and therefore true hover interaction);
  * whether or not user can use multitouch

I understand, that these traits are not user-agent based (though it would be nice to have uniform API to extract all traits needed!), but still usability of `mobile` flag is doubtful

4. Detecting webview and app brand. Webviews are different from native browsers in many ways; WKVebView in iOS differs from UIWebView. Furthermore, apps tend to impose some limitations on webview, like banning some protocols (most notably `tel:`) and disabling page scaling. It would be nice to have traits for these limitations too, or at least detect which app opens webview (right now apps use UA for this prupose)

**Comment by yoavweiss** [comment]
Thanks for the use cases! :)

RE 1 & 2 - please see https://github.com/WICG/ua-client-hints/pull/49 on where we ended up with regards to future compat.

RE 3 - We've heard strong use cases for mobile/desktop serving. What you're describing sounds like a good use case for exposing more bits as an opt-in. Maybe as an "input mode client hint"?
See https://github.com/WICG/ua-client-hints/issues/43#issuecomment-577765183

RE 4 - WebViews can definitely add the fact that they are WebViews to the UA set. I don't think we need anything specific there though.

Closing, as I believe this answers your questions, but feel free to reopen if that's not the case. Let's continue the input mode discussion on #43.
