### ISSUE TITLE
Alignment with other work

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#132]
Align other work on privacy such as the introduction of personal identifiers, requiring per install or upgrade privacy notices and defaults separate to user agent vendors other notices, or the concept of privacy budgets aligned to people’s preferences.

See [this pull request]( https://github.com/WICG/ua-client-hints/pull/124) which incorporates experiment feedback and review from interested users and other stakeholders for proposed text changes.

**Comment by yoavweiss** [comment]
I'm having a hard time understanding what the issue here is. Can you outline a specific actionable issue?

**Comment by jwrosewell** [comment]
A lot has happened since these experimental ideas were first proposed earlier in 2020. The UK’s CMA have recommended common personal identifiers as a remedy for competition issues in the [digital online marketplace](https://www.gov.uk/cma-cases/online-platforms-and-digital-advertising-market-study#final-report). Such identifiers will have a significant impact on all proposals and work with privacy as justification. Given this proposal seems to be at least in part solving a problem related to privacy the proposal will be impacted and should be aligned to this broader requirement.

The report recognizes the need to maintain existing use cases and features until alternatives are found that create a level playing field. As such this proposal is dependent on defining alternative solutions for all the use cases listed.

Regulators including the European Commission have identified dominant vertically integrated market participants maintain their dominance by capturing agreement for all products and services at the point of accepting consent for an essential service. Therefore, a dominant player may obtain consent and access to information that is practically denied to their competitors.

The TPAC session this afternoon might be an opportunity to discuss this in more detail.

**Comment by miketaylr** [comment]
It's still not clear to me how to make this request actionable beyond "align with other work". If you have a specific, concrete proposal, please file a new issue for discussion. Thanks.

**Comment by jwrosewell** [comment]
As an example. The document links to this URL https://github.com/mikewest/privacy-budget

It is neither a Normative or Informative reference and the version is not referenced. The document is on a personal GitHub repository.

The privacy budget is now an important part of Google's agreement with the CMA. The work on UACH should be aligned to that wider work. Perhaps you could seek guidance from your colleagues as part of the training you are receiving in relation to the commitments concerning how you are required to do that? If you have not received the required training could you let ING know please.

I would prefer to as a minimum receive a link to the detailed information concerning how this proposal relates to others under the title 'Privacy Sandbox' before any further changes are deployed to the market.
