### ISSUE TITLE
Default policy

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#134]
What is the policy for classifying some Client Hints as being sent by default? Either all Client Hints should be sent on every request, or no Client Hints sent on first request. If the rationale for the specification is to limit entropy then sending a value will increase entropy for minority browser vendors, whilst decreasing it for dominate browser vendors. This places minority browser vendors at a disadvantage. If the rationale is to address historic issues with the `User-Agent` field value construction this could be better addressed via a simpler specification to introduce a more modern convention for the field.

See [this pull request]( https://github.com/WICG/ua-client-hints/pull/124) which incorporates experiment feedback and review from interested users and other stakeholders for proposed text changes.

**Comment by jwrosewell** [comment]
I suppose this could be a duplicate concerning the definition of high low entropy IF the concept of restricting information is not dependent on these terms in any way. If default are dependent on high and low entropy then they will need to be defined a policy for catagorising them defined.

**Comment by yoavweiss** [comment]
The rationale of sending some hints by default (brand, version and mobileness) was to significantly reduce the entropy exposed by user agent information while still addressing many of the [use cases](https://github.com/WICG/ua-client-hints#use-cases) by default.

The use cases that were deemed critical to enable by default:
* Differential serving - community feedback we got was that this is a [critical use-case](https://groups.google.com/a/chromium.org/g/blink-dev/c/A4wxFpvqUfA/m/bzCc9XW0CgAJ) for both [polyfill serving](https://groups.google.com/a/chromium.org/d/msgid/blink-dev/d5087dcc-aa14-4907-85c2-085a5ca3b5b5%40chromium.org) and bug workarounds.
* Analytics - folks working on less-tested browsers expressed concerns that without accurate analytics, sites will not care about testing in their browser, resulting in compatibility issues. Therefore, it seems like a major use-case to enable.
* Mobile site content adaptation - [community feedback](https://github.com/WICG/ua-client-hints/issues/15) indicated that this use case is a critical one, and exposing the extra entropy to enable it is worthwhile.

As a [response](https://groups.google.com/a/chromium.org/g/blink-dev/c/A4wxFpvqUfA/m/yBjL6B0QDgAJ) to said community feedback, we adjusted the exposed-by-default hints of this proposal.

Note that browsers are still free to e.g. mimic other browsers when sending those by-default hints, in case they care more about exposed entropy than the above use-cases.

**Comment by miketaylr** [comment]
Not sure there's a point to keeping this issue opened, the question has been answered.
