### ISSUE TITLE
Question `Not\\A\Brand version: 99` what's the full meaning of this

### ISSUE THREAD

**Issue by ayumi-cloud** [WICG/ua-client-hints#137]
Pardon for me sounding dumb!

I've got a user agent example:

```
Chromium version: 88, Google Chrome version: 88, ;Not\\A\Brand version: 99
```

So I get the following:

- Chromium version: 88
- Google Chrome version: 88

I get that it's not a brand using a chrome browser like emm let's say a `Yandex` browser (which is a chrome browser from the top of my head). So the label `Not a brand` gets added - that's my guess ?

- Not\\A\Brand version: 99

I don't get the version 99 bit.

Please can you explain this: `Not\\A\Brand version: 99` part of the user agent.

Thanks.

**Comment by yoavweiss** [comment]
Does https://wicg.github.io/ua-client-hints/#grease help clarify things?

**Comment by ayumi-cloud** [comment]
Typo in spec:

> In order to avoid sites from barring unknown browsers from their allow lists, Chrome could send a UA set that includes `an` non-existent browser, and which varies once in a while.

should be:

> In order to avoid sites from barring unknown browsers from their allow lists, Chrome could send a UA set that includes `a` non-existent browser, and which varies once in a while.

----

> Does https://wicg.github.io/ua-client-hints/#grease help clarify things?

No not really, because the spec is saying:

> In order to enable equivalence classes based on Chromium versions, Chrome could add the rendering engine and its version to that.

```
"Chrome"; v="73", "NotBrowser"; v="12", "Chromium"; v="73"
```

So the spec is basically saying the integer part is the `version` number.

So to me it makes more sense seeing this:

```
Chromium version: 88, Google Chrome version: 88, ;Not\\A\Brand
```

and not this:

```
Chromium version: 88, Google Chrome version: 88, ;Not\\A\Brand version: 99
```

I don't get the `version: 99` part ?

**Comment by miketaylr** [comment]
One possible interpretation could be that `Not\\A\Brand` product is on a different release cadence that is not tied to Chromium versions. Or it is, but it switched to Chromium at version 11.

But these possible interpretations don't really matter. The point is you can't rely on a particular UA set to gate content or functionality behind -- it could change on you (in meaningless ways). `Not\\A\Brand`, or `NotBrowser`, or anything else is just an arbitrary string that is *not* the real thing. But it forces you to be careful in how you're using the UA set information. 

Does that help clarify?

**Comment by ayumi-cloud** [comment]
Yes that makes sense to me now, thanks.

**Comment by amtunlimited** [comment]
Just to add, these "extra brands" may add backslashes and the like to ensure that you're properly parsing escaped strings according to the [Structured Header spec](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html)
