### ISSUE TITLE
Platform brand values are not specified. Should there be a table or registry?

### ISSUE THREAD

**Issue by othermaciej** [WICG/ua-client-hints#142]
The `[Sec-CH-Platform hint](https://wicg.github.io/ua-client-hints/#sec-ch-platform)` says it should provide "information about the platform on which a given user agent is executing", and elsewhere is defined to be the platform brand. To the extent this header field is useful to servers, it's potentially an interop issue if different UAs send different values for the same platform. 

The set of platforms is potentially rather open-ended. Perhaps there could be some sort of registry where platform owners define the preferred brand string?

**Comment by miketaylr** [comment]
On platforms that Gecko, Blink, and WebKit ship on, there is agreement on the following platform brand values, as they ship in UA strings:

`Windows NT`, `Macintosh`, `X11`

Other platform brands where there is (some-ish) alignment between Gecko and Blink:

`Linux`, `Android`

A table documenting these would be fairly low-effort, but that's not a future-proof solution.

references:
https://source.chromium.org/chromium/chromium/src/+/master:content/common/user_agent.cc;l=32-48?q=user_agent
https://searchfox.org/mozilla-central/source/netwerk/protocol/http/nsHttpHandler.cpp#1003-1019
https://github.com/WebKit/webkit/blob/950143da027e80924b4bb86defa8a3f21fd3fb1e/Source/WebCore/platform/glib/UserAgentGLib.cpp#L48-L55

**Comment by othermaciej** [comment]
This raises further questions:

* Why the`Macintosh` token rather the `Mac OS X` token? It seems like the platform version is meant to be the OS version, so it probably should come from the OS token, not that first OS/hardware/etc token. I think that first token is supposed to be a representation of the hardware type, not the OS.

For reference here's the Mac Safari UA string:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
```

* Since UA Client Hints represent an opportunity to change possibly regrettable older names, it would be better if the macOS platform brand could be `macOS` instead of `Macintosh` or `Mac OS X`. Is that possible? 

* On iOS, the tokens in the equivalent spots are `iPhone` and `iPhone OS`, but in a new modern format, it would be better if the platform name could be `iOS`.

* The fact that these values are assumed but not stated in the spec has made it difficult to even usefully review this specific client hint, so I guess that's all the more reason to put in at least a table of known values.

**Comment by miketaylr** [comment]
So I just realized my comment was documenting existing `<platform>` tokens from today's UA strings, which isn't necessary what "platform brand" is. Chrome's current implementation returns "Mac OS X", rather than "Macintosh".

**Comment by othermaciej** [comment]
Even more reason to document "platform brand" values. 

(And I think for macOS the platform brand should ideally be `macOS`; it's possible the OS will be renamed again someday bu `Mac OS X` has not been the name of any product since 2012, so better not propagate it into new APIs.)

**Comment by miketaylr** [comment]
Yeah, agreed we should do something here.

**Comment by miketaylr** [comment]
I think we can close this now. We're going to land the "macOS" change in Chromium as well.
