### ISSUE TITLE
SHOULD-level requirement to "deprecate" User-Agent is unclear

### ISSUE THREAD

**Issue by othermaciej** [WICG/ua-client-hints#145]
[Section 5.1](https://wicg.github.io/ua-client-hints/#user-agent) says:

> User agents SHOULD deprecate the User-Agent header in favor of the Client Hints model described in this document. 

What does "deprecate" mean? In various contexts this has been taken to mean removing a feature entirely, or showing some sort of warning to the user or the developer. Even though this is SHOULD-level, it would be good to use a more specific term.

Later the section talks about freezing the value of the `User-Agent` header, but it's not clear if this is meets what is intended by "deprecate".

Maybe the SHOULD-level requirement should be specifically to freeze the value or remove the header entirely rather than using the less specific term "deprecate"

**Comment by miketaylr** [comment]
> Maybe the SHOULD-level requirement should be specifically to freeze the value or remove the header entirely rather than using the less specific term "deprecate"

This sounds reasonable.
