### ISSUE TITLE
Explainer examples of sending client hints are not compliant with the spec because they lack GREASE values

### ISSUE THREAD

**Issue by othermaciej** [WICG/ua-client-hints#147]
The [examples here](https://github.com/WICG/ua-client-hints#for-example) in the explainer send `Sec-CH-UA` without any of the mandatory GREASE values. Probably better not to have a misleading example.

**Comment by othermaciej** [comment]
Te examples here also lack the Grease treatment: https://github.com/WICG/ua-client-hints#as-a-concrete-example-what-ua-string-would-chrome-on-ios-send

**Comment by miketaylr** [comment]
This is fixed now, thanks for reporting @othermaciej
