### ISSUE TITLE
Explainer should not suggest that the controversial "Privacy Budget" proposal will solve fingerprinting

### ISSUE THREAD

**Issue by othermaciej** [WICG/ua-client-hints#149]
The [Spam filtering and bot detection] section of the explainer suggests that Privacy Budget will be a solution to fingerprinting. At this time Privacy Budget is an experimental Chrome proposal that is not even in incubation yet, and which has drawn criticism from other browser vendors. It would probably be better to avoid taking a stance on this controversy, even though the explainer is not normative.

**Comment by miketaylr** [comment]
I don't think it's harmful to link to the Privacy Budget ideas, but I'll add some language to make it more obvious that it's a proposal.

**Comment by miketaylr** [comment]
Thoughts @othermaciej?

**Comment by miketaylr** [comment]
I'm going to go ahead and close, but feel free to comment with suggestions on how we can improve the text the linked PR added.

**Comment by othermaciej** [comment]
Upon belated review, those changes look good.
