### ISSUE TITLE
Sec-CH-Mobile needs to be a default

### ISSUE THREAD

**Issue by chrisgraham** [WICG/ua-client-hints#15]
Being able to optimize responses to mobile from the offset is very important. For example, we might be returning lower-fidelity images, or different CSS, or an entirely different site, to mobile users.

Therefore if the old-school UA string is going away, we need `Sec-CH-Mobile` to be available by default.

I'd definitely advise to not assume every mobile-friendly site is doing things with 100% responsive design. There are very legitimate reasons for taking other, or hybrid, approaches.

**Comment by n8schloss** [comment]
Strongly agree with this. Additionally as we advocate more for [adaptive loading ](https://www.youtube.com/watch?v=puUPpVrIRkc), and not merely changing based on screen size it's important for a server to know up front what type of site to serve.

Without 'Sec-CH-Mobile' being sent by default I think we'll see many sites introduce a redirect step for them use JS on the initial page load to check if the browser is mobile or not and then to redirect to a mobile site if it is.

**Comment by jonarnes** [comment]
To know whether the "thing" that sent the request is a mobile or not is important, I agree. Many many sites depend on this knowledge. However, like discussed earlier in the forum, the definition of "mobile" may vary. From a UX perspective, how is the mobile form factor defined? Is Google/Chrome the right party to define this for your site and audience? I'm not sure I'd like that.

**Comment by chrisgraham** [comment]
Right, it is kind of a can of worms. Our software product has configurability right now based on user-agent. If that's going away, we need at least something that works on first request and works server-side. Going beyond a simple binary opens up a whole conversation about what dimensions are relevant and whether we can even define those dimensions in a future-proof way.
For example:
1. Connection speed
2. Cost of bandwidth
3. Screen size
4. Mouse vs Touchscreen
I think I'd argue a simple binary has pragmatic value for most use cases, and anything else can be handled via CSS and JS APIs.

**Comment by n8schloss** [comment]
> I think I'd argue a simple binary has pragmatic value for most use cases, and anything else can be handled via CSS and JS APIs.

I agree

**Comment by erikg-dev** [comment]
Can't fathom CDNs not being able to detect the device on first request. For various reasons many web apps are generated and cached on the edge according to the Cloudfront-Is-* headers. Would be huge step backwards for developers if these headers were no longer available.

**Comment by yoavweiss** [comment]
https://github.com/WICG/client-hints-infrastructure/pull/20 turns on Sec-CH-Mobile by default, so will close this issue

**Comment by yoavweiss** [comment]
Related PRs landed. Closing
