### ISSUE TITLE
Explainer question about neutering the JavaScript interface has an unclear referent

### ISSUE THREAD

**Issue by othermaciej** [WICG/ua-client-hints#150]
https://github.com/WICG/ua-client-hints#do-we-really-need-to-neuter-the-javascript-interface-too

> Do we really need to neuter the JavaScript interface too?

What is this referring to? The explainer (like the spec) describes a JavaScript interface that has access to all the same info as can be retrieved via HTTP, so in what way is it neutered? This question should probably explain what it's talking about.

**Comment by amtunlimited** [comment]
The interface is "neutered" in comparison to the current option in JS, `navigator.userAgent`, in the same way the header is. I'll try to clarify that.
