### ISSUE TITLE
Abuse protection

### ISSUE THREAD

**Issue by vyv03354** [WICG/ua-client-hints#16]
How can this spec prevent websites from blocking browsers that do not send `Sec-CH-UA`? OK, sooner or later, all browsers will have to send `Sec-CH-UA` for web compatibility. Then, how can this spec prevent websites from [blocking](https://vivaldi.com/blog/user-agent-changes/) browsers that send `Sec-CH-UA: "Vivaldi"`?

Please do not pollute HTTP headers with yet another garbage forever.

**Comment by yoavweiss** [comment]
https://wicg.github.io/ua-client-hints/#grease outlines thoughts on that front. Closing as this is not actionable, but feel free to re-open if more discussion is needed.
