### ISSUE TITLE
Create a working group

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#176]
It seems like there is now enough interest in this proposal and those that it relates to progress to the working group stage where the ideas will benefit from the W3C Process. Can the WICG chairs advise on what would be needed to start this process?

**Comment by sideshowbarker** [comment]
One necessary step is to create a draft charter. At https://w3c.github.io/charter-drafts/charter-template.html you can find a template

**Comment by jwrosewell** [comment]
I'm happy to work with others to draft a working group charter. Perhaps the group would be titled "Client Information Working Group". I have some experience of this having drafted the now stalled [Decentralized Web Interest Group](https://w3c.github.io/charter-drafts/decentralized-charter.html) (DWIG) charter.

Overall the additional rigor associated with the W3C Process will help ensure consensus across all participants, not just browser vendors, prior to mass deployment.

**Comment by jwrosewell** [comment]
I notice on the Blink group there are folks asking about the next steps with this proposal. Can I assume that the lack of comments on this issue show a disinclination to follow the W3C Process?

**Comment by miketaylr** [comment]
Hi @jwrosewell,

This proposal is still in its early stages. In line with the [W3C process](https://www.w3.org/2020/Process-20200915/), we are currently focused on working through open issues and better understanding missing use-cases. If and when there is broad enough interest to move this work to a WG, the W3C staff would be the ones to assess whether to make that transition, following the W3C process related to WGs. 

cc @wseltzer @plehegar

Thanks.

**Comment by jwrosewell** [comment]
Google have communicated to the market that they will be deploying this proposal. Is now the right time to re-open this issue and progress to Working Group stage so that W3C Process can be applied?
