### ISSUE TITLE
Add Acknowledgments section

### ISSUE THREAD

**Issue by miketaylr** [WICG/ua-client-hints#180]
It's nice to recognize contributions, so let's add one.

It won't be perfect, but we can start by asking folks who have contributed if they consent to be included, then ask folks to add their name as they have approved PRs.

**Comment by amtunlimited** [comment]
Running `git log --format='%aN <%ae>' | sort -u` gives the following:

```
Aaron Tagliaboschi <aarontag@chromium.org>
jasonwee <peichieh@gmail.com>
Luke <lgardener1337@gmail.com>
Luke Williams <19214773+lukewlms@users.noreply.github.com>
Mike Taylor <miketaylr@google.com>
Mike West <mike@mikewest.org>
Mike West <mkwst@chromium.org>
Mike West <mkwst@google.com>
Toru Kobayashi <koba0004@gmail.com>
Yoav Weiss <yoav@yoav.ws>
```

**Comment by miketaylr** [comment]
@koba04, @ArkUmbra, @lukewlms, @jasonwee, @mikewest, @amtunlimited  - please let me know if you would like to *opt out* of showing up in an Acknowledgements section by next week or so.

(leaving out myself and yoav, current editors are implicitly acknowledged imho)

**Comment by miketaylr** [comment]
OK, I see no comments objecting here. So I'll proceed.

(We can always remove names from the spec if folks change their minds).
