### ISSUE TITLE
This spec shouldn't allow whitespace and add some basic validation rules

### ISSUE THREAD

**Issue by ayumi-cloud** [WICG/ua-client-hints#185]
Today I see this CH-UA:

```
" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
```

![image](https://user-images.githubusercontent.com/57409060/104920718-1fe20180-5990-11eb-91f9-aa2692be0749.png)

Notice the whitespace before the ` NOT A;Brand" why does this spec not remove the whitespace?

Also I would like to point out that the user agent spec actually has some validation rules, see here:

https://tools.ietf.org/html/rfc7230#section-3.2.6

It would be nice if the CH-UA also should them.

**Comment by amtunlimited** [comment]
> Also I would like to point out that the user agent spec actually has some validation rules, see here:
>
> https://tools.ietf.org/html/rfc7230#section-3.2.6
>
> It would be nice if the CH-UA also should them.

All of the User-Agent Client Hints follow the [Structured Header format](https://datatracker.ietf.org/doc/draft-ietf-httpbis-header-structure/) which is compliant with Section 3.2.6. Specifically, the Sec-CH-UA header is a list, where each item is a quotes string with a "v" parameter that denotes major version.

The "brand" you're pointing out is designed to trip up non-compliant header value and Structured Header parsers, which means odd (but compliant) characters in semi-random places. See [the GREASE section of the draft](https://wicg.github.io/ua-client-hints/#grease) for a full explanation. There is nothing in either spec that disallows a space at the beginning of a quoted string.

**Comment by ayumi-cloud** [comment]
Thanks for the info.
