### ISSUE TITLE
Update tokens to be consistent with Client Hints I-D

### ISSUE THREAD

**Issue by miketaylr** [WICG/ua-client-hints#186]
This landed in Chromium today(ish): https://bugs.chromium.org/p/chromium/issues/detail?id=1153688

**Comment by miketaylr** [comment]
Per https://tools.ietf.org/html/draft-ietf-httpbis-client-hints-15#section-3.1, the tokens should match the header that is sent. So we need to update the spec here to reflect that requirement.

**Comment by amtunlimited** [comment]
Missed an example.
