### ISSUE TITLE
Define getters for read-only attributes (Was: interface NavigatorUAData should be a dictionary)

### ISSUE THREAD

**Issue by domenic** [WICG/ua-client-hints#19]
As this is not a class with a useful constructor, data, and behavior packaged together, but instead a simple holder for data, it would be better as a dictionary.

**Comment by domenic** [comment]
This would also solve the problem where the getter algorithms for each field of NavigatorUAData are not defined, and instead https://wicg.github.io/ua-client-hints/#dom-navigatorua-getuseragent somehow sets the value of readonly getter fields.

**Comment by yoavweiss** [comment]
We've [reached the conclusion](https://github.com/WICG/ua-client-hints/issues/39) that it might be better off to remove the Promise from `getUserAgent()`'s return value, and add it on single attributes. I believe that design is not possible with a dictionary, so we would need to properly define the getters.

**Comment by yoavweiss** [comment]
#48 is the PR in which we're moving the promises.
There may be work left after it though (e.g. explicitly setting the getters on the read only attributes)

**Comment by yoavweiss** [comment]
I believe this was addressed by https://github.com/WICG/ua-client-hints/pull/70.
