### ISSUE TITLE
can "major version" include minor version?

### ISSUE THREAD

**Issue by myakura** [WICG/ua-client-hints#20]
> major version (for example: "72", "3", or "28")
https://wicg.github.io/ua-client-hints/#user-agent-major-version

The name and the examples imply major version only accepts integer. But there are user agents whose major versions are not enough to distinguish their feature sets between releases.

Notably Safari. Apple has been introducing new features in the "x.1" releases for the past few years.
(e.g. 12.1 https://webkit.org/blog/8718/new-webkit-features-in-safari-12-1/ )

And there's curl, which has been [7.x for nearly two decades](https://curl.haxx.se/changes.html#7_1).

So, does that _majorness_ mean _effectiveness_? In either case it needs clarification.

**Comment by yoavweiss** [comment]
This was filed earlier than #23 (apologies...), but as there's already lively discussion happening there, it might be better to close this one as a duplicate. Closing, but feel free to chime in on #23

**Comment by myakura** [comment]
no probs!
