### ISSUE TITLE
Biblio entry for RFC8942 missing

### ISSUE THREAD

**Issue by rowan-m** [WICG/ua-client-hints#203]
Quick one for @miketaylr- looks like #199 updated `([[I-D.ietf-httpbis-client-hints]])` references to `([[!RFC8942]])` but didn't include the new entry for it.

```
$ bikeshed spec
LINE ~130: Couldn't find 'RFC8942' in bibliography data. Did you mean:
  rfc2119
  icc42
  mrcpv2
  bcp47
  jf2
 ✘  Did not generate, due to fatal errors
```

**Comment by miketaylr** [comment]
Hey @rowan-m, apologies -- I missed this one coming through.

I'm not able to reproduce, can you run `[bikeshed update](https://tabatkins.github.io/bikeshed/#cli-update)` and re-try?

**Comment by miketaylr** [comment]
(Gonna preemptively close, but please re-open or comment if somehow my setup is borked, it wouldn't be the first time).
