### ISSUE TITLE
Sec-CH-UA-Arch doesn't show my architecture.

### ISSUE THREAD

**Issue by bat999** [WICG/ua-client-hints#205]
Hi
Using the demo at https://user-agent-client-hints.glitch.me/

Sec-CH-UA-Arch doesn't show my architecture.

Is this OK?

I expected it to say Sec-CH-UA-Arch: "ARM"

![CH_UA_demo](https://user-images.githubusercontent.com/640761/108642184-9f855380-749b-11eb-9d52-621eb7c3119e.jpg)

**Comment by amtunlimited** [comment]
FYI this repo is for the spec itself; this is an implementation issue.

I will, however, go ahead and tell you that this is WAI for Chrome. See [crbug #1078270](https://crbug.com/1078270). Only Windows and Linux actually return an architecture for `Sec-CH-UA-Arch`; all other platforms give a blank value.

Can I ask what your use case is for needing the arch on Android?

**Comment by bat999** [comment]
Hi amtunlimited

From the crbug link I can see that Sec-CH-UA-Arch has been discussed.
And, like you said...
"Only Windows and Linux actually return an architecture for Sec-CH-UA-Arch; all other platforms give a blank value."

And with my Linux Desktop PC the demo does show arch...

```
Sec-CH-UA: "Chromium";v="87", "\"Not;A\\Brand";v="99"
Sec-CH-UA-Mobile: ?0
Sec-CH-UA-Full-Version: "87.0.4280.66"
Sec-CH-UA-Platform: "Linux"
Sec-CH-UA-Platform-Version: 
Sec-CH-UA-Arch: "x86"
Sec-CH-UA-Model:
```

(It probably doesn't show Sec-CH-UA-Model because it's an old banger, lol)


"Can I ask what your use case is for needing the arch on Android?"

I don't need to know the arch, I was just trying out the demo.
I followed links from https://www.chromestatus.com/features/schedule
Chrome 89 FEATURES PLANNED IN THIS RELEASE:
Sec-CH-UA Client Hints

Thanks for your help and clarification.

:-)
