### ISSUE TITLE
Link to https://w3c.github.io/fingerprinting-guidance/ for passive entropy references

### ISSUE THREAD

**Issue by miketaylr** [WICG/ua-client-hints#214]
See https://github.com/WICG/ua-client-hints/issues/200#issuecomment-801220103.

**Comment by jwrosewell** [comment]
The document linked in the title of this issue does not address the concerns raised in the original comment concerning the justification for the proposal. Only those references from the linked document that provide evidence of actual harm in practice can be used to justify the proposal and address the original comment. I would hope we can agree theoretical harm is not the same as actual harm.

Consider the X-Client-Data example. Chrome transmits to a whitelist of Google owned domains an HTTP header named X-Client-Data. This is described by Google [here](https://www.google.com/chrome/privacy/whitepaper.html#variations). The value could be used for identification purposes when combined with other available values. Therefore theoretical harm exists. This theoretical harm has been addressed by Google using a document that describes how the information is used.

The same principles exist elsewhere. A web site operator must in their privacy policy describe any identifiers, including probabilistic identifiers. Theoretical harm is similarly addressed. The proposal made no attempt to consider similar remedies that involve professions other than engineering, such as the law. This issue provides an opportunity to address that with evidence and a clear explanation as to why other remedies do not apply in this situation.

**Comment by miketaylr** [comment]
> The document linked in the title of this issue does not address the concerns raised in the original comment concerning the justification for the proposal.

If you can file a new issue (or @ronancremin, it seems the both of you shared similar concerns) to discuss that concern, that would be appreciated, especially since that concern came up in an unrelated issue. 

This issue is just a task issue for me to add some hyperlinks, so I'd prefer it stay a simple task. Thanks!

**Comment by miketaylr** [comment]
(I can also file an issue, but going to be OOO for a few days)

**Comment by ronancremin** [comment]
Done: #215

**Comment by jyasskin** [comment]
This spec should cite https://w3c.github.io/fingerprinting-guidance/#avoid-passive-increases in particular, which explains why passive entropy is worse than active: "Passive fingerprinting allows for easier and widely-available identification, **without opportunities for external detection** or control by users or third parties."

**Comment by jwrosewell** [comment]
@jyasskin Thanks for pointing to the section on the theoretical harm. Is there any evidence of actual harm that can be pointed to for issue #215?

**Comment by jyasskin** [comment]
I'll keep this as a task issue, as @miketaylr requested, but answer on #215.
