### ISSUE TITLE
UAs SHOULD have more than a single brand value (Was: Stronger encouragement on set of UA strings)

### ISSUE THREAD

**Issue by domenic** [WICG/ua-client-hints#22]
https://github.com/WICG/ua-client-hints#should-the-ua-string-be-a-set indicates an idea of there being a set of user agents.

Although it is unclear why this would be a good idea (#21), if we assume it's desirable, I worry that the current design does not do enough to encourage web developers to treat the UA list as a set. Unless early browser implementations follow this optional part of the spec, I imagine we'll see a lot of parsing code for Sec-CH-UA which assumes there's only a single value. (See also https://github.com/WICG/ua-client-hints/issues/7#issuecomment-574263079.) This will effectively prevent any later browser from ever implementing the optional steps in the spec, because doing so would break server assumptions.

Additionally, the JS API always returns a single string, not a set.

If the intention is to encourage treating the UA as a set of possible UAs, then I think you need to make changes such as:

- Changing Sec-CH-UA to a structured header list of strings, instead of a structured header string.
- Potentially mandating, or at least strongly suggesting, that browsers always include >= 2 items in the list. (Especially early implementations.)
- Change the JS API so that `getUserAgent()` returns a promise for an array of `NavigatorUAData`s, or possibly change `NavigatorUAData`'s `platform` and `version` members to be arrays instead.

**Comment by yoavweiss** [comment]
I believe this is closed by #46. #49 adds various explanations that are also related.

The only thing missing is a SHOULD for including more than a single item.
