### ISSUE TITLE
getHighEntropyValues should also include low-entropy values

### ISSUE THREAD

**Issue by jridgewell** [WICG/ua-client-hints#222]
https://github.com/ampproject/amphtml/pull/33621/files#diff-abe5d4569e4d12320aedbcda58f9816e73e0aef3a01a0608934a27b5ef0b6811R1173 adds new code that requests a `platform` CH via `getHighEntropyValues`:

```js
const values = await navigator.userAgentData.getHighEntropyValues([
  'platform',
]);

assert.notEqual(values.platform, undefined);
```

But, `platform` is [about to be a low-entropy value](https://github.com/WICG/ua-client-hints/pull/221). When this happens, requesting `platform` as a high-entropy value will not add it to to the returned `UADataValues` object. This means https://github.com/WICG/ua-client-hints/pull/221 is a breaking change.

We can either keep `platform` as the lone low-entropy value accessible from `getHighEntropyValues`, or we should just add all low-entropy values to `UADataValues`.

**Comment by miketaylr** [comment]
Thanks for filing the issue @jridgewell. My original thinking for Chromium (which is separate from the spec) was to deprecate `platform`, but have `platform` exist in both places (as a readonly attribute, and accessible in the resolved `gHEV` promise) for some period of time before removing.

However, it's conceivable that hints may move from high- to low- entropy in the future and we'd have to deal with this again. I think your proposal of also making low-entropy hints available inside the UADataValues object sounds reasonable.

**Comment by miketaylr** [comment]
Let's wait on #221 to be merged, but the change to enable this is pretty simple:

In https://wicg.github.io/ua-client-hints/#getHighEntropyValues, in step 3, after step 1, add each of the low-entropy hints (unconditionally).

**Comment by jridgewell** [comment]
Works for me, thanks!
