### ISSUE TITLE
Consider a markup-based method to delegate to non-iframe resources

### ISSUE THREAD

**Issue by miketaylr** [WICG/ua-client-hints#232]
For example, perhaps `allow` could be extended to work with `<img>`, `<script>`, `<link>`, etc.

One use-case for `<link>` is for CSS that varies on platform version to know which web fonts to serve.

**Comment by amtunlimited** [comment]
I feel like it would be particularly helpful for script tags, even outside the CH context

**Comment by miketaylr** [comment]
I think we can close this in favor of https://github.com/WICG/client-hints-infrastructure/issues/73
