### ISSUE TITLE
UA-CH and HTTP statelessness 

### ISSUE THREAD

**Issue by ronancremin** [WICG/ua-client-hints#237]
From its inception the HTTP protocol has been stateless by design. It's stated explicitly in the Abstract section of the RFC's for HTTP 1.0 and HTTP 1.1:

> It is a generic, stateless, protocol which can be used for many tasks…

The RFC for HTTP 2.0 states:

> HTTP's existing semantics remain unchanged.

HTTP was designed such that each request should contain enough information on its own to fulfill the request. 

In the User-Agent Client Hints proposal, if a server seeks detailed information about the user agent making a request, it must add an Accept-CH header in its response and await the next request to obtain the Sec-CH-UA hints. But a server cannot tell the difference between a new request from a previously unseen user agent and a request where a user agent has opted to withhold the sought Sec-CH-UA hints for its own reaons. This effectively forces the server to maintain state about whether or not each user agent has been seen previously or not in order to decide what to do. 

This appears to go against the design principles of the HTTP protocol. "Automated recognition of user agents for the sake of tailoring responses" is specific use case outlined in the HTTP protocol, but this use case will become more difficult for implementors with the User-Agent Client Hints proposal.

**Comment by Sora2455** [comment]
I believe the intended solution to this problem is "[Critical Client Hints](https://github.com/WICG/client-hints-infrastructure/blob/main/reliability.md#critical-ch)", where you get the client to re-send their request if they would have added the client hints.

**Comment by ronancremin** [comment]
Right but this still requires the cooperation of the user agent which might be configured to never send Sec-CH-UA headers due to user preference.

**Comment by miketaylr** [comment]
HTTP is a stateless protocol, yes. But session state exists (i.e., Cookies).

That said, this repo is not the right venue for this discussion. UA-CH doesn't invent any new mechanisms for HTTP, it's just an application of [Client Hints](https://datatracker.ietf.org/doc/html/rfc8942).

The HTTP WG mailing list is probably the right place to bring up your concerns for rfc8942: https://lists.w3.org/Archives/Public/ietf-http-wg/

**Comment by ronancremin** [comment]
I should have been clearer. My point was that UA-CH effectively forces a developer to manage state for a use case that would not previously have required it. 

> That said, this repo is not the right venue for this discussion. UA-CH doesn't invent any new mechanisms for HTTP, it's just an application of Client Hints.

I agree that UA-CH doesn't invent any new mechanisms—it's more that it forces the use of a mechanism which will impact  developers and thus deserves consideration as part of UA-CH.
