### ISSUE TITLE
Considerations for Spam/Fraud Detection

### ISSUE THREAD

**Issue by AramZS** [WICG/ua-client-hints#24]
Hi all,

Interesting stuff! I've examined the documentation and the first thing that pops into my head is how much UA is used in detecting digital advertising (and general traffic spam) fraud. I'm going to be connecting up with vendors who we work with for whom this might be a concern to get a read on what they feel like the impact will be, but I anticipate some concern. I'm wondering if there's some preexisting thought on how this might impact that detection? 

Thanks!

**Comment by yoavweiss** [comment]
I'm not sure what the exact use-case is for spam/fraud-detection, and would be happy if you could expand on it. If I'd had to guess what you mean, I'd end up with something that looks a lot like user fingerprinting...

The general area of privacy-preserving fraud detection is tackled by the [Trust Tokens](https://github.com/WICG/trust-token-api) proposal. Can you take a look to see if it would solve your use-case?

/cc @csharrison

**Comment by csharrison** [comment]
I'm not sure if trust tokens is useful here. That API is all about propagating trust from site to site, whereas detecting anomalous behavior (like unusual UA patterns) might be about acquiring that initial trust signal.

**Comment by yoavweiss** [comment]
@AramZS - Can you expand on how the UA string is being used for fraud detection?

**Comment by yoavweiss** [comment]
#30 contains a concrete example, and as I suspected, it seems indistinguishable from user fingerprinting...

**Comment by yoavweiss** [comment]
I've added [this use-case](https://github.com/WICG/ua-client-hints#spam-filtering-and-bot-detection) as an explicit one we want to enable.

IIUC, "fingerprinting for good", including fraud detection, would still be enabled by access to the UA information through a header based opt-in or through the JS API.

Anything else you'd like to see on that front? Or can we close this?

**Comment by yoavweiss** [comment]
Closing as this has been silent, but please let me know if more discussion is needed and I'll reopen.
