### ISSUE TITLE
Implementation pattern for content adaptation use case

### ISSUE THREAD

**Issue by ronancremin** [WICG/ua-client-hints#240]
This may not be the correct place to raise this question, but it probably needs to be discussed somewhere. 

Websites that currently use server-side content adaptation rules to adapt content to devices typically use the device's User-Agent header as an input for adaptation decisions. 

Prior to the availability and deployment of [ALPS and ACCEPT_CH HTTP/2 and HTTP/3 frames](https://chromestatus.com/feature/5555544540577792), is there a recommended implementation pattern for the content adapation in the case of user agents which support UA-CH?

As I see it, implementors will have to do a couple of things:

1. Maintain a list of frozen UA strings to inform step 2 
2. In the case of a first visit from a user agent thought to support UA-CH, redirect back to the same URI in order to obtain the desired `Sec-CH-UA-*` hints.
3. Serve adapted content informed by the UA-CHs.

This seems fine but it seems likely that user agents may be configured to suppress UA-CHs either globally or on a per-domain basis. In this case web servers won't know the difference between a first visit from a particular user agent and a user agent that is choosing not to send UA-CHs despite the server's request.

This appears to require a cookie or some other means of tracking state on the server side. It might be useful for the proposal or some other document to cover some implementation patterns.

**Comment by miketaylr** [comment]
Thanks for the issue @ronancremin.

> It might be useful for the proposal or some other document to cover some implementation patterns.

Yeah, it probably doesn't belong in the spec proper, but developer guidance on how to migrate to UA-CH does seem like a good idea. https://web.dev/migrate-to-ua-ch/ exists (not complete by any means). MDN might also be a good place for this kind of advice. Or even some content in this repo's wiki.

**Comment by amtunlimited** [comment]
> In the case of a first visit from a user agent thought to support UA-CH, redirect back to the same URI in order to obtain the desired Sec-CH-UA-* hints.

Small note, this concept (of redirecting if necessary hints are missing) can be covered client-side by by using a Critical-CH header, covered by the [Server-side hints required on first request](https://web.dev/migrate-to-ua-ch/#strategy:-server-side-hints-required-on-first-request) section.

**Comment by miketaylr** [comment]
I filed https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues/16 to cover this, thanks for filing @ronancremin.
