### ISSUE TITLE
What is the fingerprint threat model that warrants completely freezing the UA string and requiring web devs to move to UA client hints?

### ISSUE THREAD

**Issue by mikesherov** [WICG/ua-client-hints#25]
Title of the issue not intended to be snarky! I'm of the opinion that invalidating existing os, vendor and version browser sniffing comes with it a high bar,  as it's essentially equivalent to a Web Platform intervention. To this effect, it seems like there would need to be a clear security benefit (like with defaulting to SameSite: lax) and/or performance benefit (defaulting to passive scroll listeners) to warrant this change. Arguments about ergonomics are nice to haves in my opinion when faced with the amount of work web devs will have to do to deal with this, so that leaves security as the main issue here in my opinion.

So, as someone who heard about this change via the intent to deprecate being posted, my naive question is: 'what security benefit does a complete freeze get us that a partial freeze wouldn't? By partial freeze, I mean locking the string except for OS version / Browser Vendor / Browser Version (or whatever UA-CH aims to provide).

It seems like the answer is "the string wouldn't be sent by default... just for those who request it", but what actual threat model is there fingerprinting-wise from *just os version / Browser Vendor + Version* being detectable in the UA that is fine grained enough to warrant this change?

That is, the fingerprinting argument on those 3 pieces of information seems small enough of an attack vector compared to things like IP address that the benefit we get from switching to opt-in isn't big enough, when switching to partial freeze (like Safari) gets us almost all the way there.

Said even another way, what is an example attack or fingerprinting threat that exists solely on a partially frozen UA string in a request?

**Comment by domenic** [comment]
> It seems like the answer is "the string wouldn't be sent by default... just for those who request it"

Note that Sec-CH-UA, i.e. brand + version, is sent by default.

So I think your question boils down to contrasting two possible models:

- The currently-proposed one, where brand + version are sent by default over HTTPS and other info is explicitly requested, vs.
- Maintaining the current User-Agent header and navigation.userAgent API, but only allowing their brand + version pieces to vary between browsers.

I think the currently-proposed model has the following advantages, apart from ergonomics:

- HTTPS only. Identifying even the user's brand + version is a powerful feature.
  - This advantage could be oviated by sending the same navigator.userAgent/User-Agent to every non-secure site.
- More likely to be web-compatible. I don't think we could get everyone to converge on navigator.userAgent/User-Agent header values that only vary in brand + version; changing the user agent string is too fraught. Starting over allows a clean slate for browsers to align on.

**Comment by mikesherov** [comment]
Ok, so:

> HTTPS only. Identifying even the user's brand + version is a powerful feature.
This advantage could be oviated by sending the same navigator.userAgent/User-Agent to every non-secure site.

So this doesn't seem like it has a threat model nor powerful advantage.

> More likely to be web-compatible. I don't think we could get everyone to converge on navigator.userAgent/User-Agent header values that only vary in brand + version; changing the user agent string is too fraught. Starting over allows a clean slate for browsers to align on.

How is it more compatible then freezing what we have now minus brand + version?

As a spectator here who will have to do work to support this change, it really doesn't sound like the benefits stated so far are compelling for a web BC breaking intervention? Or am I thinking about it wrong?

**Comment by domenic** [comment]
I'll let the proposal authors take over from here.

**Comment by yoavweiss** [comment]
Browser brand and major version will still be exposed by default in the new scheme, so from a privacy threat perspective, that's very similar to the freezing scheme you're proposing.
Platform will not be exposed, and will require a server opt-in.

Regarding the privacy threat model, exposing platform by default would have added a few bits of entropy, which would vary based on the user's OS (where minority OSs expose more bits than majority ones).

*But*, that's not why we're adding this brand new scheme. We're adding a brand new scheme because we're recognizing that one the one hand content adaptation based on the UA string has valid use cases, and on the other, we need to avoid broadcasting that information to servers that do not need it.

Partially freezing the UA string without providing an alternative (to provide access to the "frozen" parts) would have not enabled sites that really do need that information to request it.

**Comment by mikesherov** [comment]
Thanks for the response, Yoav. I appreciate your engagement on this.

> Partially freezing the UA string without providing an alternative (to provide access to the "frozen" parts) would have not enabled sites that really do need that information to request it.

Yes, adding a new scheme is fine. It's the *full* freezing of the old scheme that essentially makes this feel like an intervention. an intervention by letter is "when a user agent decides to deviate slightly from a standardized behavior in order to provide a greatly enhanced user experience". Although UA sniffing for brand, version, and "mobile/not mobile" isn't a de jure standard, it's a defacto one.

If the plan is only a partial freeze of UA, such that brand and version can still be detected, then 👍. If the plan is to full freeze UA, then 👎 

> and on the other, we need to avoid broadcasting that information to servers that do not need it.

In spirit, I agree with principle of least information. However, this still doesn't explain what real fingerprinting could be done with *just* brand and version being exposed via UA (in the case of a partial UA freeze) to insecure sites?

**Comment by yoavweiss** [comment]
> However, this still doesn't explain what real fingerprinting could be done with _just_ brand and version being exposed via UA (in the case of a partial UA freeze) to insecure sites?

From a privacy perspective, a UA string which continues to update the major/significant version would not expose any new information. At the same time, it will continue to expose users to the same kind of compatibility issues they are now facing due to bad UA sniffing.

My thinking behind freezing the version (brand doesn't change, so freezing it is meaningless) was that all cases that use the version number to determine something today (e.g. work around bugs) will continue working just fine into the future, but new UA related code will have to move to the new infrastructure. Does that make sense?

**Comment by mikesherov** [comment]
Yes your position makes sense but I don't agree with the conclusion. Permit me to dig a bit deeper :-)

> From a privacy perspective, a UA string which continues to update the major/significant version would not expose any new information. At the same time, it will continue to expose users to the same kind of compatibility issues they are now facing due to bad UA sniffing.

Ok so it sounds now like the benefit is it will force people who have *already* poorly implemented UA sniffs to use a new system that is less prone to error. 

**However**, it won't fix any site that already has this problem. It'll only hope to make some of those folks to switch. 

And, it offers no benefit to folks who already have proper UA sniffs and browser version detection already working. Just more work to get back what they already have.

It seems that freezing the UA except browser version, AND providing UA-CH gives us the best of both worlds: working implementations continue to work, upgrade path for those that have already screwed it up.

**Comment by mikesherov** [comment]
> I my experience with numerous projects, "folks who already have proper UA sniffs and browser version detection already working" don't exist in the long term. They exist at best for a short time, and then issues arise.

I also too have lots of experience, and I've personally never had this problem. There's quantitative numbers on this stuff, but even still...

> I would have expected people using such UA sniffing to be the best proponents of UA-CH, so that they job is easier and more robust. 🤷‍♂️

Sure,  UA-CH is a better API, which is why it should exist. But that's different from saying people *must* switch. There are plenty of people who have working UA implementations who don't want to have to do unnecessary work.

**Comment by mikesherov** [comment]
@yoavweiss i read this post on the intent to deprecate:

![82E82AE8-47A1-44E5-9133-962F4108340F](https://user-images.githubusercontent.com/364532/72651250-d01dc400-3950-11ea-8f18-dc8e344fa9e5.jpeg)

And I just wanted to say thanks for listening to the feedback and adjusting! It's really appreciated! I'll consider this issue closed for now.
