### ISSUE TITLE
CH headers List

### ISSUE THREAD

**Issue by rokii** [WICG/ua-client-hints#251]
Does this readme list all CH headers https://github.com/WICG/ua-client-hints/blob/main/README.md?

**Comment by miketaylr** [comment]
@rokii relevant to User-Agent Client Hints, yes. But there are other Client Hints headers, i.e., https://developers.google.com/web/updates/2015/09/automating-resource-selection-with-client-hints

Are you looking for all the UA hints, or _all_ hints?

**Comment by miketaylr** [comment]
Let's close here as inactive, but feel free to keep commenting. :)

**Comment by rokii** [comment]
> @rokii relevant to User-Agent Client Hints, yes. But there are other Client Hints headers, i.e., https://developers.google.com/web/updates/2015/09/automating-resource-selection-with-client-hints
> 
> Are you looking for all the UA hints, or _all_ hints?

thanks for the info. I just need UA hints

**Comment by miketaylr** [comment]
Cool. https://wicg.github.io/ua-client-hints/#http-ua-hints is probably the safer place to reference. But yes, the README has them all as well.
