### ISSUE TITLE
FrozenArray in dictionaries

### ISSUE THREAD

**Issue by dontcallmedom** [WICG/ua-client-hints#258]
#250 includes https://github.com/miketaylr/ua-client-hints/commit/281a8e83696a25819d2caf1d4492a76d1ae91d8c which turns a number of dictionary members from `sequence`s to `FrozenArray`s, which I understand is almost never a good idea per https://github.com/heycam/webidl/issues/900

(spotted in https://github.com/w3c/webref/pull/350)

**Comment by miketaylr** [comment]
Yeah, we can update this (it was not super intentional).
