### ISSUE TITLE
Request size bloat, UA URIs

### ISSUE THREAD

**Issue by timriker** [WICG/ua-client-hints#268]
This proposal starts with the assumption that too much information is  being added to the UA string.

I don't see anything in the spec that talks about reducing information. We're freezing the current information and adding quite a few more fields that will now tell the remote site what version of windows the client is running, etc.

It seems like this spec is growing the UA string into multiple headers, each of which can be requested individually and none of which have a plan for future deprecation.

Presumably site statistics will want to know everything they can about users, so they will request all available information so that statistics can be broken out by browser, os, version, eye color, whatever is available.

I'm not a fan. Deprecating what can be removed from the UA header would be nice. Adding more information is not the preferred direction. I'd rather see an official user agent published url that can identify all features an agent supports.

User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 https://chrome.example.com/94.0.4606.81

or eventually:

User-Agent: https://superbrowser.example.com/99.20301215

That page could then be loaded and cached on the server side, to determine how to operate with the given User-Agent. Then by all means add whatever details you want. The browser-version url could be platform specific, architecture specific, or the browser vendor could choose to hide all that and have a generic version url.

The user can, of course, choose to send a different UA string and will, as they do today, have to deal with the consequences.

The goal would be to get to a user-agent capability list that is *not sent with every artifact* loaded for a given page.

Let's reduce the network load, not increase it by growing what needs to be sent with every single tiny request. Point Someplace Else (tm) for all that detail.

**Comment by timriker** [comment]
Agent and version could be unique to a hardware platform, ie:
User-Agent: https://nifty.example.com/arm64/3.2.1.20300101

You cite that the information might not be accurate. As far as I can see, that exact issue exists if the browser supplies it. In fact a lot of the work today is trying to identify bugs in the browser that are not represented directly in the User-Agent string. Presumably they would not be represented in the browser supplied UA headers either.

PoorBrowser v0.0.1 say it supports CSS Grid, awsome, here's grid stuff. Oops, browser lied. The site can ask for the UA headers, and STILL have to look up someplace to determine if they can be trusted.

The URI reference has the advantage that a vendor could blacklist features after finding them in the field.

Of course the URI reference also has the disadvantage that the vendor could blacklist feature whenever they choose.

The user would be able to override the URI supplied on some browsers, just as we can override the current User-Agent field.

I would anticipate that sites like https://caniuse.com/ would publish their own, probably more detailed and more accurate, list for browsers and users may choose to point their URI there instead of the OEM's URI. Pretty much anything that caniuse.com lists are potential things a site would want to know from a UA. The list of fields requested could grow to be far longer than the current UA strings in a very, very, short time.

I would not propose XML for the data, like UAProf used, and instead recommend json as simpler and harder to get wrong.

My comment is: don't put it in the request at all. If I know what UltimateBrowser 97 can handle, then I don't want to ask every visitor to my site the same questions. Putting it in the headers invites every site to ask for every header so that they can look later and see what's statistically significant. This just slows down the user experience.

We already have issues with overall header size on many applications. We don't need to open the floodgates to many more headers, IMHO.

**Comment by jwrosewell** [comment]
The draft report also includes the addition of GREASE that is deliberately adding useless information. As such the draft report remains inconsistent in it's objectives.

There is a [timeline](https://privacysandbox.com/timeline/) associated with deployment. It is having a meaningful market impact. The proposal should move to a Working Group #176 so that the W3C Process can apply and these inconsistencies can be resolved via the [W3C Process](https://www.w3.org/Consortium/Process/).

**Comment by Niek** [comment]
I think it's strange how the reasoning goes from: "the `User-Agent` header exposes too much entropy" to: "let's add all these new client hints exposing a bunch of additional entropy". FYI, this is what's currently exposed in Chrome Canary on my MBP:

<img width="1013" alt="Screenshot 2021-12-09 at 08 46 28" src="https://user-images.githubusercontent.com/213140/145355029-4ee10ea3-53ce-4d1e-b662-1df378288896.png">

Re the argument "but this isn't sent by default, unlike the UA": it is, if you specify these client hints as `Critical-CH` they are sent in the first GET request, even in a fresh context. See https://headers.cf/ for a sample.

**Comment by Sora2455** [comment]
Yes, but if you specify all of those headers in Critical-CH then browsers are supposed to either not provide all of them or to restrict other functionality once the privacy sandbox really kicks in.

**Comment by miketaylr** [comment]
> "let's add all these new client hints exposing a bunch of additional entropy"

It's not additional entropy, as far as the UA-CH hints are concerned - this is all available in the UA string. Beyond that I suppose you've learned this browser "supports client hints" (which is the default Chrome behavior since 89, but the UA string already told you the user was on Chrome >= 89).

> "but this isn't sent by default, unlike the UA": it is, if you specify these client hints as Critical-CH

If is doing a lot of work there! And this is the point of Critical-CH (nit, it's _not_ actually the first request - the navigation is restarted internally when it sees Critical-CH).

**Comment by Niek** [comment]
> > "let's add all these new client hints exposing a bunch of additional entropy"
> 
> It's not additional entropy, as far as the UA-CH hints are concerned - this is all available in the UA string. Beyond that I suppose you've learned this browser "supports client hints" (which is the default Chrome behavior since 89, but the UA string already told you the user was on Chrome >= 89).

My issue is mostly with the non-`Sec-CH-UA-*` client hints that add loads of extra entropy, but even the UA-CH hints are exposing more info than the old UA string. For example: the OS version is more detailed (Win 10 vs 11, macOS 10+) and arch has never been part of the regular UA string on non-Linux browsers AFAIK (e.g. M1 vs Intel Macs).

> > "but this isn't sent by default, unlike the UA": it is, if you specify these client hints as Critical-CH
> 
> If is doing a lot of work there! And this is the point of Critical-CH (nit, it's _not_ actually the first request - the navigation is restarted internally when it sees Critical-CH).

I know that's the point of the Critical-CH header, my 2c is that this makes the "it doesn't expose all this info right away" argument obsolete (at least in the current implementation).

**Comment by miketaylr** [comment]
> For example: the OS version is more detailed (Win 10 vs 11, macOS 10+) 

Can you explain what you mean here? It's not more detailed from what I can see, it's just an accurate value compared to the frozen parts of the UA string.

> and arch has never been part of the regular UA string on non-Linux browsers AFAIK (e.g. M1 vs Intel Macs).

UA strings on Windows have and do expose that. For the macOS example, `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36'`, Intel is pretty prominent, right? Historically there has been a "PPC" token. I would not expect Apple to expose M1 in the UA string in the future, but I cannot speak for Apple. 

That said, UA-CH only exposes 2 values: "x86" and "arm" (technically 3, it's conforming for a browser to return "").

> my 2c is that this makes the "it doesn't expose all this info right away" argument obsolete (at least in the current implementation).

I disagree. When we talk about passive fingerprinting, the point is the browser sends all the info by default with all requests and has no idea what sites are doing to collect it. If a site is sending Accept-CH or Critical-CH, the browser does know the site is requesting it and make decisions accordingly. This is non-default in the sense that this info is not sent... by default for any site without such headers (which is more or less the entire web today).

**Comment by Niek** [comment]
Maybe this more suitable for a separate discussion, but I'll respond here for now:

> > For example: the OS version is more detailed (Win 10 vs 11, macOS 10+)
> 
> Can you explain what you mean here? It's not more detailed from what I can see, it's just an accurate value compared to the frozen parts of the UA string.

The UA of Windows 10 and Windows 11 are exactly the same. The same counts for macOS 10.15.7 and any newer macOS version. The UA of a M1 and Intel macOS machine are the same as well. This is something different than a frozen UA string, which unifies the UA string across all browsers - the UA client hints simply expose more info.

> > and arch has never been part of the regular UA string on non-Linux browsers AFAIK (e.g. M1 vs Intel Macs).
> 
> UA strings on Windows have and do expose that.

I have Windows 11 running on arm64, and it shows this in Edge (there is no arm64 build of Chrome on Windows, so I can't check there):
```
sec-ch-ua-arch: "arm"
sec-ch-ua-platform-version: "14.0.0"
User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43
```

There is no sign of arm in the UA string, and Windows 11 is only listed in the UA client hints (i.e. more entropy).

> For the macOS example, `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36'`, Intel is pretty prominent, right? Historically there has been a "PPC" token. I would not expect Apple to expose M1 in the UA string in the future, but I cannot speak for Apple.

See https://source.chromium.org/chromium/chromium/src/+/main:content/common/user_agent.cc;l=77-78
There is no distinction between the architectures in the UA string on macOS.

> That said, UA-CH only exposes 2 values: "x86" and "arm" (technically 3, it's conforming for a browser to return "").
> 
> > my 2c is that this makes the "it doesn't expose all this info right away" argument obsolete (at least in the current implementation).
> 
> I disagree. When we talk about passive fingerprinting, the point is the browser sends all the info by default with all requests and has no idea what sites are doing to collect it. If a site is sending Accept-CH or Critical-CH, the browser does know the site is requesting it and make decisions accordingly. This is non-default in the sense that this info is not sent... by default for any site without such headers (which is more or less the entire web today).

While I agree there is a theoretical distinction, in practice it means that every single site out there can request full entropy for any URL that is loaded - at least in the current implementation.

**Comment by miketaylr** [comment]
> Maybe this more suitable for a separate discussion

Perhaps yes, I think we're possibly talking past each other a bit. Feel free to open a new issue and maybe we can find some alignment. :)

**Comment by miketaylr** [comment]
Thanks for the discussion everyone - there's some interesting ideas in this issue. @timriker I encourage you to flesh out your User-Agent capabilities URL idea and perhaps propose it to the [wicg discourse](https://discourse.wicg.io/) to see if you can pick up support from other developers or browser vendors. As far as this draft spec is concerned, it runs counter to its goals so I'm going to close here.
