### ISSUE TITLE
Navigator Platform

### ISSUE THREAD

**Issue by dgstpierre** [WICG/ua-client-hints#278]
In fraud detection, the navigator.platform is used very differently than the operating system that is specified in the user agent.  Am I understanding correctly that platform is being removed?  Spoofing the user agent and hence the operating system is very common.  Platform is very helpful in detecting that.

**Comment by miketaylr** [comment]
This specification doesn't cover `navigator.platform`, and says nothing about its removal. 

That said, Chromium is going to "freeze" platform to one of a few values: https://www.chromium.org/updates/ua-reduction#TOC-Reduced-navigator.platform-values-for-all-versions-. Perhaps one day it will make sense to specify that in [HTML](https://html.spec.whatwg.org/#dom-navigator-platform), if other browser engines do the same.
