### ISSUE TITLE
What's the rationale for `getUserAgent` returning a Promise?

### ISSUE THREAD

**Issue by kenrick95** [WICG/ua-client-hints#28]
The current situation with `navigator.userAgent` is that it is synchronous, but the proposed `navigator.getUserAgent()` is asynchronous (returning a Promise). I assume there should be a rationale behind this and would like to know the reason.

Thank you

**Comment by lm1** [comment]
It does not seem to help anybody. It's a fast non-blocking operation. If this is going to be used anywhere in conditional rendering it's a significant hindrance, especially if legacy UA string path must be maintained.

**Comment by mikewest** [comment]
Making the getter asynchronous allows the browser an opportunity to make a decision about whether or not to reveal some piece of information to the page or not. Some user agents may decide they need to ask the user for permission to reveal this kind of information, which is ~impossible to do if the API is synchronous.

**Comment by kenrick95** [comment]
Thanks @mikewest for the response! That's a really great rationale.

Do we need to mention this rationale somewhere in the spec? If you think it's not necessary, my question has been answered and we can close this ticket. 😁 

Thank you

**Comment by mikewest** [comment]
@yoavweiss, @amtunlimited: WDYT? Want to work up a PR?

**Comment by foolip** [comment]
Making this async seems like it will make it much harder to adapt existing code, and I wonder if the benefits will really be worth it.

What amount of entropy is exposed in synchronous getters like `screen.width` or `navigator.hardwareConcurrency`? If there are enough such cases already, isn't the plan to mitigate those good enough to also cover any new APIs that would be most natural to make synchronous?

**Comment by mikewest** [comment]
I'm trying not to bite off an even bigger problem with the first pass at this API, but it seems pretty obvious to me that things like `hardwareConcurrency` ought to move to the same model we're proposing here, perhaps even living as a member on this exact API.

`screen.width` is a different can of worms, being dealt with in places like https://github.com/webscreens/screen-enumeration/blob/master/EXPLAINER.md (which I'd note is also async).

**Comment by foolip** [comment]
Will at least the contents of https://wicg.github.io/ua-client-hints/#sec-ch-ua be available as a synchronous API, given that it's sent by default with all requests? If no sync alternatives exists for the basic case, then I predict someone is going to offer a library, maybe built on https://modernizr.com/, to infer the browser from the supported feature set. That would lead to all sorts of silly places.
