### ISSUE TITLE
Identifying well-behaved bots

### ISSUE THREAD

**Issue by dgstpierre** [WICG/ua-client-hints#281]
Being able to identify well-behaved bots that currently identify themselves in the user agent seems to be missing.

**Comment by miketaylr** [comment]
If a well-behaved bot were to identify via UA-CH, it would be fine to do that in the brand list: https://wicg.github.io/ua-client-hints/#user-agent-brand.

**Comment by dgstpierre** [comment]
So if I understand your answer, for example, GoogleBot would be in the brand list?

**Comment by miketaylr** [comment]
> So if I understand your answer, for example, GoogleBot would be in the brand list?

I think that would make sense, but I can't speak for the GoogleBot team.
