### ISSUE TITLE
Why browser brand and not engine brand?

### ISSUE THREAD

**Issue by arvind-m** [WICG/ua-client-hints#29]
The motivation statement for (browser) brand and version mixes a couple:

> Brand and version information (e.g. "Chrome 69") allows websites to work around known bugs in specific releases that aren't otherwise detectable. For example, implementations of Content Security Policy have varied wildly between vendors, and it's difficult to know what policy to send in an HTTP response without knowing what browser is responsible for its parsing and execution.

The first sentence implies that is it not uncommon for sites to be testing every version of browsers that are important to them, and to be deploying fixes for issues found in specific browser versions.

But the example provided speaks to differences in implementation _across browser engines_ that the site will care about. Assuming that the example illustrates the predominant use of browser brand (and optionally version), then it logically follows that Sec-CH-UA (perhaps appropriately renamed) should indicate the browser engine name and not the brand.

If this is missing an important point or two, can you update the explainer to clarify the reasons for surfacing the brand via client hints?

Thanks

**Comment by RByers** [comment]
+1 to this concern. More generally I am quite worried about the more rigid API structure of CH relative to a free-form string. The ability for engines to express concepts like "Yes I am WebKit, but I am also Chrome" (or "I am Chrome, but I am also Edge" etc.) has been absolutely essential to how UA strings have been used in practice. Any API that doesn't naturally lead to that semantics (i.e. that leads developers to ask "are you Chrome" in a way that would say no to "Edge") seems likely to fail to me (will become meaningless - eg. with more "lying" by engines than even what we see in the UA string). 

Maybe the API should be such that there's always a set and the simplest thing for developers to do is to ask "is X in the set" (not "is X the first thing in the set" or "is X the only thing in the set"). I.e. it's not "what is the browser's brand or engine" it's "is this browser compatible with browser/brand X".

**Comment by yoavweiss** [comment]
Agree that a set is the right approach. That would enable browsers to say things like "Chrome; 81, Chromium; 81, Opera; 68" and be able to express both their "equivalence set" as well as their own brand.

I've heard concerns that a separate `Sec-CH-UA-Engine` hint would result in making it hard for different embedders of a single engine to e.g. ship different features. A set that mixes browser and engine brands seems less prone to that (or at least won't make it harder than it already is).

**Comment by yoavweiss** [comment]
Also, see https://github.com/WICG/ua-client-hints/issues/22

**Comment by amtunlimited** [comment]
I think one point that's not brought up is that this proposal was (at least originally) made to have a 1-to-1 parity with the information put into the User-Agent header. There is a benefit to doing so for backwards compatiblity, as the idea was that the only thing you really need to change was what header you're reading from and the regex and the rest of the logic could remain

> Agree that a set is the right approach. That would enable browsers to say things like "Chrome; 81, Chromium; 81, Opera; 68" and be able to express both their "equivalence set" as well as their own brand

This is what I've been envisioning.

**Comment by yoavweiss** [comment]
See further discussion on UA set vs. explicit engine information at https://github.com/WICG/ua-client-hints/issues/21#issuecomment-578648776
