### ISSUE TITLE
`Sec-CH-UA` vs `Sec-CH-UA-Full-Version-List`

### ISSUE THREAD

**Issue by summercms** [WICG/ua-client-hints#291]
Currently updating our parser code to process the new `Sec-CH-UA-Full-Version-List` and got a bit confused at first.

It would of made more sense if `Sec-CH-UA` was renamed to `Sec-CH-UA-Short-Version-List` then I would have clicked straight away.

The reason for opening this issue is because I think the spec should mention the difference between `Sec-CH-UA` vs `Sec-CH-UA-Full-Version-List`.

For example adding a line like this in the spec would have prevented me getting confused:

> The headers `Sec-CH-UA` and `Sec-CH-UA-Full-Version-List` are exactly the same with the only difference `Sec-CH-UA` shows the **major** semantic version value only and `Sec-CH-UA-Full-Version-List` shows the full semantic version value. To learn more about the semantic versioning see here: https://semver.org/

**Comment by miketaylr** [comment]
Thanks for the feedback @summercms! I'm not sure it makes sense to link to semver - most browsers these days treat major versions as a regular marketing moment, either monthly or bi-annually. And minor can sometimes indicate security releases, ESR updates, stability updates, etc.

But... I agree we can make this less confusing.
