### ISSUE TITLE
GREASE-like UA brand lists should be careful not to introduce new fingerprinting surfaces

### ISSUE THREAD

**Issue by caraitto** [WICG/ua-client-hints#292]
The [explainer](https://github.com/WICG/ua-client-hints#should-the-ua-string-really-be-a-set) and [spec](https://wicg.github.io/ua-client-hints/#grease) mention that a GREASE-like approach can be used to prevent abuse of brand lists. 

While this should help prevent such abuse, care should be taken so that the GREASE-like UA brand lists don't themselves introduce a new fingerprinting vector. For instance, if each client computes a random GREASE-like UA brand at startup that will be used for all navigations in all tabs, this could serve as such a fingerprinting vector. However, if the identifier is consistent for many users (all users of browser version X have the same GREASE-like UA brand) or unstable (a new GREASE-like UA brand is generated every network request in an unpredictable manner), then the GREASE-like UA brand won't serve as an effective fingerprinting vector.

The explainer, spec, and privacy / security questionnaire should all mention this risk and require implementations mitigate this fingerprinting scenario.

**Comment by miketaylr** [comment]
Thanks for the feedback @caraitto. Right now the spec leaves GREASE randomization up to the UA, but we can add some guidance on what could go wrong.
