### ISSUE TITLE
`Sec-CH-UA-Platform-Version` header and `platformVersion` in the steps of `getHighEntropyValues()` doesn't point to the same text

### ISSUE THREAD

**Issue by makotoshimazu** [WICG/ua-client-hints#299]
Hi,

I found those two descriptions are not referencing to the same thing when I crawl the spec.
- [getHighEntropyValues](https://wicg.github.io/ua-client-hints/#getHighEntropyValues) looks up [user-agent-platform-version](https://wicg.github.io/ua-client-hints/#user-agent-platform-version) and it says `The user agent's operating system’s version. (e.g., "NT 6.0", "15", or "17G")`
- [sec-ch-ua-platform-version](https://wicg.github.io/ua-client-hints/#sec-ch-ua-platform-version) looks up its own logic.

They sounds slightly different according to the example, but I'm guessing they are expected to be the same.
Is my understanding correct?

Thanks!

**Comment by miketaylr** [comment]
Thanks! I'll fix this up.

**Comment by makotoshimazu** [comment]
No problem, thanks!
