### ISSUE TITLE
Awareness of location for User Agent Reduction issues

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#300]
The CMA have published their first [report](https://assets.publishing.service.gov.uk/media/62835bfee90e071f6af1457e/Privacy_Sandbox_Progress_Report_to_the_CMA_2022_Q1.pdf) following the commitments agreed with Google in February 2022.

> Going forward, Google plans to monitor several metrics, including: Net.HttpResponseCode (material changes in the number of requests that failed to deliver content), ClientHints.StoreLatency (captures the time it takes, in milliseconds, to store the client hints for an origin in the PrefsService), ClientHints.FetchLatency (captures the time it takes, in milliseconds, to retrieve the client hints for an origin from the PrefsService, that will be added to the outgoing HTTP request headers), ClientHints.CriticalCHRestart (measures the number of times a navigation had to be restarted in order to include the requested client hints on the initial navigation) and PageLoad.PaintTiming.NavigationToFirstContentfulPaint (measures the latency, in milliseconds, from the time the navigation stats to the time the response first statss getting painted to the screen). Google will also work with partner teams, both internal and external, to receive feedback and metrics on client hints latency from the server’s perspective and will monitor community reports through [Chromium](https://bugs.chromium.org/p/chromium/issues/list?q=component:Privacy%3EFingerprinting) and issues reported on the [Github](https://github.com/miketaylr/user-agent-reduction/issues) repository.

The GitHub repository for raising reports is one under @miketaylr's account which I was unaware was a Google official location for raising issues on such changes.

**Comment by miketaylr** [comment]
Thanks for the feedback James. Given that this repo is for feedback related to the UA-CH proposal—not UA Reduction—I will close this issue. If people prefer to provide feedback as bug reports against the Chromium project, rather than GitHub issues, they can do so in the [bug tracker](https://bugs.chromium.org/p/chromium/issues/list?q=component:Privacy%3EFingerprinting) you linked above.
