### ISSUE TITLE
Truthfulness 

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#307]
Remove phrases such as "return the empty string or a fictitious value" to ensure that the specification can be relied upon to be truthful and not interfere with interoperability.

**Comment by miketaylr** [comment]
@jwrosewell the UA string can't be trusted today, so it doesn't seem realistic to require anything different here. For the most part, I would expect UAs to send truthful values, but they should be free to send spoofed values for compatibility or privacy purposes.

**Comment by miketaylr** [comment]
Thanks for the feedback, but I don't think we plan to make any changes here.
