### ISSUE TITLE
Is it really necessary to deprecate navigator.appVersion, navigator.platform, navigator.productSub and navigator.vendor?

### ISSUE THREAD

**Issue by NotLazy** [WICG/ua-client-hints#317]
On websites I've made that utilize Ctrl keyboard shortcuts, I've used navigator.platform to determine if the machine is mac, to modify those shortcuts into Cmd keyboard shortcuts. Maybe there's a better way, but the point is, why must we go through navigator.userAgentData just to get any low entropy values? Could we not simply continue to provide them via known and documented routes?

Before client hints were implemented in Chrome, navigator.platform returned "MacOS" but now that chrome has begun freezing data, it returns "MacIntel", which, even if it's wrong since I'm actually on Arm, feels like it's returning more data than before. Could we not have the specification just change these values to target client hints instead, since, via client hints, I can get the original "MacOS" from navigator.userAgentData.platform?

I know this is a very minor change, and really begs the question of "why can't you just add the .userAgentData before .platform?" but I feel like it's a waste to deprecate more JS features than just the userAgent.

**Comment by miketaylr** [comment]
> Before client hints were implemented in Chrome, navigator.platform returned "MacOS"

@NotLazy can you describe which platform version + Chrome version this is true for? Thanks. Presumably M1 mac? Something else?

**Comment by NotLazy** [comment]
I'm not sure how to downgrade exactly since I have automatic updates turned on to be able to test for you, but definitely before chrome 100

**Comment by miketaylr** [comment]
OK - I'm unable to verify that (though I did not check all 99 version before 100 :)). As for the "deprecation" of these APIs - in reality, they will not disappear. Too much legacy web content depends on them. Instead, they will be "frozen".
