### ISSUE TITLE
Discriminates against people in developing countries

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#32]
As just one exmaple.

10s of millions of people in Sub-Saharan Africa recieve their news from web sites optimised for feature phones (they still exist), smart phones and desktops using mobile networks where they pay per MB. Is anyone considering their needs?

The User-Agent HTTP header is used to identify the device at first request and adapt according to the device and network. This change will slow the web down for all these people. At worst it'll degrade their experience to make access to basic news uneconomical.

Whilst the change makes engineering sense it appears there are a significant set of unintended consequences yet to be considered.

**Comment by yoavweiss** [comment]
I reject the premise of this issue.

To be clear, performance and in particular performance on low end devices in poor network conditions is near and dear to my heart.

There's a long list of features (that I've worked on) that enable avoiding to send extraneous data to folks that don't need it or cannot afford it:
* The [Network information API](https://wicg.github.io/netinfo/) (and Client Hints headers) enable sites to adapt their site when the user is in rough network conditions.
* The [Save Data API](https://wicg.github.io/savedata/) (and Client Hints headers) enable sites to adapt to their user's preference and make better tradeoffs about the size of their resources.
* [Responsive images](http://responsiveimages.org/) (the `<picture>` element and the `srcset` attribute) enable site developers to define multiple resources that fit multiple user situations related to their screen density, viewport sizes and more.
* [Image Client Hints](https://www.smashingmagazine.com/2016/01/leaner-responsive-images-client-hints/) enable server-side adaptation based on DPR, Viewport-Width and explicit image width when one is available to the browser.

> The User-Agent HTTP header is used to identify the device at first request and adapt according to the device and network

Network information is not included in the current `User-Agent` string that the browser sends.

> using mobile networks where they pay per MB. Is anyone considering their needs?

The `User-Agent` string doesn't currently include any information on the network conditions, its costs, or the user's preferences.
