### ISSUE TITLE
Breadth of feedback

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#322]
The [3rd quarterly report produced by Google](https://assets.publishing.service.gov.uk/media/63592e16d3bf7f0bd41962bc/Privacy_Sandbox_Progress_Report_to_the_CMA_2022__1.pdf) under their commitments to the UK CMA references feedback regarding fraudulent clicks. The report claims that companies (plural) have provided positive feedback and links to issues #314 and #315 in this repository. These issues are further linked to via a [Google web page](https://developer.chrome.com/blog/user-agent-reduction-oct-2022-updates/#feedback-and-testing) covering User-Agent reduction.

The issue raised on behalf of VTEX(@tibuurcio) references partners at ClearSale(@Camila-Villamarin) and CyberSource. It  is not clear to the reader if one experiment was conducted with two issues raised, or two independent experiments were conducted and reported. 

Assuming two experiments were conducted and resulted in positive indications concerning impact I consider this insufficient evidence to conclude that “certain features” won’t be lost for a far wider cohort of stakeholders.

Have Google approached the [antifraud community group](https://www.w3.org/community/antifraud/participants) to obtain confirmation from a larger cohort of interested parties that there is no impact on payment and fraud use cases? What other methods have Google used to proactively gain feedback? Why did Google not reference the issues provided in this repository, and in @miketaylr's [personal repository](https://github.com/miketaylr/user-agent-reduction/issues/11) relating to readiness?

Please can Google (tagging @miketaylr, @cwilso, @yoavweiss) provide a substantive answer in the January 2023 quarterly report provided to the CMA and the industry under the [commitments](https://www.gov.uk/cma-cases/investigation-into-googles-privacy-sandbox-browser-changes) which I believe Google employees at W3C have now been trained in.

**Comment by miketaylr** [comment]
We are committed to achieving the purpose of the Privacy Sandbox commitments accepted by the CMA in February 2022. We encourage feedback on how to better achieve that purpose through our technical proposals, and we will report publicly on feedback we receive as set out in the commitments. We are in constant dialogue with the CMA on these issues, and members of the web ecosystem are also welcome to discuss these issues with the CMA. In fact, as previously mentioned by the CMA in public and in its communications to Mr Rosewell, the CMA is the sole public body responsible for monitoring Google’s compliance with the commitments accepted on 11 February 2022 in relation to Google’s Privacy Sandbox proposals. We therefore hope that everyone will understand when we decline to participate in public discussions on legal or internal aspects of compliance with the commitments, or to detail our direct exchanges with the CMA.
