### ISSUE TITLE
Privacy Sandbox Timelines: In Development?

### ISSUE THREAD

**Issue by thegreatfatzby** [WICG/ua-client-hints#346]
Hello friends, I'm confused on something.

In the Privacy Sandbox [timelines](https://privacysandbox.com/open-web/) I see "User Agent Reduction" as being "In Development". However, based on some conversations with my Edge fwends and [this](https://www.chromium.org/updates/ua-reduction/) guy, it seems like User Agent Reduction is well underway, if not complete.

So, can you help me understand what, if anything, is still in development for UA Reduction?

**Comment by miketaylr** [comment]
Thanks for pointing that out - we can probably move it to Launched now (same for Network State Partitioning). I'll try to find whoever works on that site and let them know. :)

**Comment by thegreatfatzby** [comment]
@miketaylr thanks! So is UA reduction complete, as in no further changes planned?

**Comment by miketaylr** [comment]
@thegreatfatzby yep, no further changes to the UA string planned for Chrome.

**Comment by thegreatfatzby** [comment]
@miketaylr I'm sorry this isn't your responsibility, but in case you know...

Do you know, can you point me to, or can you ask someone to check, if the to other statuseses (stati?) on that page are updated?

**Comment by miketaylr** [comment]
@thegreatfatzby sure - happy to ask someone to check to make sure everything is up to date. Storage Partitioning is close to be moved to "Launched", but it's not rolling out at 100% quite yet.
