### ISSUE TITLE
Why is the name "form factor" (singular) instead of "form factors" or "form factor list"?

### ISSUE THREAD

**Issue by domenic** [WICG/ua-client-hints#355]
Before adding form factor, the spec had two list-valued fields:

- `Sec-CH-UA-Full-Version-List` HTTP header / `fullVersionList` JS API
- `Sec-CH-UA` HTTP header / `brands` JS API

Introducing form factor creates a third list field, but it follows neither of the previous two precedents. Instead it uses the singular name "form factor".

Is this perhaps an oversight when working on #343, you forgot to consider renaming?

**Comment by miketaylr** [comment]
> Is this perhaps an oversight when working on #343, you forgot to consider renaming?

Yeah, oops. @djmitche - any thoughts or preferences?

**Comment by miketaylr** [comment]
> I guess that would mean `Sec-CH-UA-Form-Factors` and `formFactors` for JS.

The shorter the better...

**Comment by djmitche** [comment]
I'll work on making this change in Chromium. If one of you can assign this issue to me it will make sure I don't forget to update it.

**Comment by dmdabbs** [comment]
Will you post to this issue the final disposition for the hint and/or to the tracking bug?

**Comment by djmitche** [comment]
I'll also update the draft spec in this repo, and the PR to do so will link here. I'm not sure what you mean by "final disposition", though.

**Comment by dmdabbs** [comment]
>I'll also update the draft spec in this repo, and the PR to do so will link here. 

The feature card (https://chromestatus.com/feature/5162545698045952) would probably also need a name change.

>I'm not sure what you mean by "final disposition", though.

From the thread here the final naming did not seem settled.

**Comment by miketaylr** [comment]
To be clear, we will rename to `Sec-CH-UA-Form-Factors`, etc.

**Comment by miketaylr** [comment]
Given https://github.com/WICG/ua-client-hints/pull/358 - I think we can close here. Thanks for the input @domenic!
