### ISSUE TITLE
How does a client disable sending high entropy hints to the browser?

### ISSUE THREAD

**Issue by prarsena** [WICG/ua-client-hints#356]
I've been exploring css media queries, UA-CH, and other aspects related to the exchange of data between the OS and a website in a [blog post](https://www.peterarsenault.industries/posts/hugo/responsive-light-dark-modes/).

In the [MDN docs for User-Agent Client Hints API](https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API), it makes mention of the differences between low-entropy and high-entropy values. Is there a way for a user to disable sending their high entropy values with their request? I saw some mention that UA-CH are safer for users than a traditional UA string, but I didn't find instructions for the user to withhold sending certain data to the server. 

Also related to the web API, is there a way to return the `Sec-CH-Prefers-Color-Scheme` value or other User Preference Media Features through `navigator.userAgentData`?  Or plans to allow this?

**Comment by Sora2455** [comment]
> In the [MDN docs for User-Agent Client Hints API](https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API), it makes mention of the differences between low-entropy and high-entropy values. Is there a way for a user to disable sending their high entropy values with their request?

That would be a question for the individual browser makers, not a spec question. IIRC, the spec only recommends that such controls are available.

> Also related to the web API, is there a way to return the Sec-CH-Prefers-Color-Scheme value or other User Preference Media Features through navigator.userAgentData? Or plans to allow this?

Out of scope of this proposal, but you want `matchMedia("(prefers-color-scheme: light)").matches` or `matchMedia("(prefers-color-scheme: dark)").matches`.

**Comment by miketaylr** [comment]
Yes, @Sora2455 is correct - this would be more in the realm of a feature request for the browser (via pref, extension, UI etc) to disable the API.
