### ISSUE TITLE
What is a user agent's brand?

### ISSUE THREAD

**Issue by foolip** [WICG/ua-client-hints#4]
https://github.com/WICG/ua-client-hints#a-proposal says:
> By default, servers should receive only the user agent's brand and major version number.

This would be delivered in the `Sec-CH-UA` header as "Chrome 74" in the example given.

Question: What should other Chromium-based browsers send? What everyone does with the UA string is to add something to the end, like "Edge/14.14393" or "OPR/43.0.2442.991".

If the `Sec-CH-UA` header is used like the `User-Agent` header, then a new Chromium-based based browser will have to send the same header as Chrome to get the content that will actually work.

A few problems here:
- How to work around bugs in a popular Chromium-based browser?
- How to collect statistics on which concrete browser (not engine) are used?

Probably the answer is the same mechanism as would be used to get other bits of information in the UA string that have been frozen, like the device model. Are there client hints for "concrete browser"? If there is, and it's practical to use it to work around bugs, will it not be locked in by web compat also? Round and round we go :)

**Comment by foolip** [comment]
Oh look, this is discussed in https://github.com/WICG/ua-client-hints#should-the-ua-string-be-a-set. That proposal looks pretty promising, actually :)

**Comment by foolip** [comment]
In addition to including random fake brands, the number of brands in the set would probably have to be varied at random, to actually allow for it to grow over time as browsers fork and multiply.

**Comment by domenic** [comment]
Is the idea here that, e.g., Chromium-based browsers would include the corresponding Chrome UA brand/version with theirs? That wasn't at all the impression I got from reading that section, but if that's the intention, it makes a lot more sense.

I'd suggest changing the example to a realistic one, if that's the intent.

**Comment by jonarnes** [comment]
And how will the `Sec-CH-UA` header behave in a native app through a webview/browser component?

**Comment by yoavweiss** [comment]
@domenic - https://github.com/WICG/ua-client-hints/pull/49 should some more realistic examples of what the set may look like and why

**Comment by yoavweiss** [comment]
> And how will the `Sec-CH-UA` header behave in a native app through a webview/browser component?

I suspect this question is slightly out of scope for the spec to answer. From a web compat perspective, I can imagine it matching the browser version on which the webview is based on, while potentially indicating that it's a webview as part of the set.
