### ISSUE TITLE
Reference "FacebookYearClass" 404 Not Foundd

### ISSUE THREAD

**Issue by Krinkle** [WICG/ua-client-hints#40]
> [FacebookYearClass]
>    Chris Marra; Daniel Weaver. Year class: A classification system for Android. URL: > https://code.fb.com/android/year-class-a-classifiation-system-for-android/ 

I've checked [Internet Archive](http://web.archive.org/web/*/https://code.fb.com/android/year-class-a-classifiation-system-for-android/) as well but no dice.

**Comment by yoavweiss** [comment]
Thanks for reporting! :)
The link is indeed broken and moved to engineering.fb.com
Fixed in https://github.com/WICG/ua-client-hints/pull/41
