### ISSUE TITLE
Add a boolean 'Sec-CH-UA-Mobile' header

### ISSUE THREAD

**Issue by amtunlimited** [WICG/ua-client-hints#5]
Most (or a least a lot) of the UA sniffing that I've seen in the real world is simply used to answer the question of whether a "mobile" or "desktop" experience should be served. It might be helpful to simply answer this question directly.

As most implementations simply check for "Android" or "iOS" for mobile and anything else is desktop, the hint would probably just be a subset of the "sec-ch-ua-platform" hint, but slightly less information and a more direct answer. It'd probably look like:

`sec-ch-ua-mobile: sh-boolean`

Where `sh-boolean` is defined [here](https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-13#section-3.9)

**Comment by amtunlimited** [comment]
Someone elsewhere pointed out that there should probably be a reasonable (or at least more explicit) definition of when this header would be true or false. My first thought would be strictly platform based, but that's not quite explicit enough.

In general, this header would affect UX, in that if it were true you'd be looking at a smaller screen more focused on touch controls, as opposed to more exact mouse & keyboard controls and more screen real-estate. 

It should also be noted that this is already implicitly defined by most modern browsers, as almost all of them have separate "mobile" and "desktop" versions that send distinct user agent strings advertising as such, and seems to be adopted by most developers that don't base UX on feature detection or screen/viewport width.

Most mobile browsers also have a "request desktop site" setting as well that this could be connected to.

**Comment by mikewest** [comment]
As a hint that folks would opt-into, this doesn't seem compelling. Developers would likely ask for something like viewport instead, and calculate a categorization on their own. We're unlikely to expose the viewport information by default, as there's a lot of entropy wrapped up in those values. Exposing some low-granularity proxy like this might be a reasonable thing to do (and, indeed, I think we were planning on doing so when freezing the existing `User-Agent` header's value anyway). 

I wonder if "mobile" is really the right concept, but I know I don't know enough about how folks develop sites today to understand the divisions they usually end up with. "Phone" vs "Desktop" is straightforward, but where do tablets fall? iPad OS just shifted to align the iPad's UA string with desktop's, which is an argument in favor of not distinguishing any more than the boolean would allow, but I wonder if we should shift to an enum for forward compat?

**Comment by amtunlimited** [comment]
One thought could be (although this would kind of step out of client hints) for the server to send a number like a viewport size and the client would answer if it's above or below. Although as I'm writing that down I realize the server could just play 20 questions to find out what the viewport size is. I'd love if we could do something similar, but I don't think we could without just giving away the viewport anyways.

We could just define a number of viewport-size-buckets, but I don't really know how much I like that. While I'm sure we could find a reasonable list, I don't know how good the tradeoff of # of buckets vs usefulness would be or how to find the right balance.

As far as I'm aware, most of the web currently defines two "mobile" and "desktop" buckets and just splits based on viewport or platform, but I'll do some more researching to be sure. I know there's a good amount of "UA to feature" look up services that can tell you things like viewport, available features, and a bunch of other stuff based on the UA string. Basically a big data-mined database you can query.

I wouldn't be opposed to an enum, but I could see that ballooning out of control or turning into just "model" with extra steps if we're not careful.

**Comment by Malvoz** [comment]
It's not clear to me, as a simple developer, how reflecting the exact viewport size would increase the security risks, considering that we already can get the information through CSS media queries.

More authoritative people discussing this in https://discourse.wicg.io/t/proposal-viewport-http-header/3233/7 haven't expressed concerns around this.

**Comment by mikewest** [comment]
> how reflecting the exact viewport size would increase the security risks

I don't think it creates security risks. I do think it increases the server's ability to identify a given device over time, as certain viewport sizes are going to be significantly less common than others. My viewport on the machine where I'm typing this response, for instance, is a full-screened Chrome using some variant of linux, displayed on 24" monitor, turned vertically. 1200x1822 is a pretty strange viewport size. Sending it out with outgoing requests can put my requests into a pretty small bucket.

The question, then, is what we're willing to expose by default. It seems reasonable to me to give developers, by default, the ability to distinguish between mobile- and desktop-style UI. It seems significantly less reasonable to give exact viewport information. If the site asks for it, great! The browser can make a reasonable decision based on whatever characteristics it feels like considering. :)

**Comment by nuxodin** [comment]
I think "mobile" true/false is not expandable enough.
Maybe "Sec-CH-UA-Variant", that can be something like

- mobile
- desktop
- tv
- watch
