### ISSUE TITLE
About adding compatible-brands fields

### ISSUE THREAD

**Issue by sonchulmin** [WICG/ua-client-hints#55]
It is very good to see mobile flag is in.
Previously 'iPhone' or 'Android' in UA string was for mobileness.

Problem is, if you think of creating new web browser based on chromium, it could be something different.
Could you add brand name as "MyNewBrowser" and expect web sites handle MyNewBrowser as chromium or chrome ?

Web sites mostly do not know about MyNewBrowser and they will give just 'default' contents even when they can send better contents that work on chromium.

Previously UA strings had web engine names that are compatible.
Some people say those are lies, but I don't think so.
It was for new browsers to say they are compatible with previously well-known browsers.

So, I propose adding compatible-brands fields so that new browsers can survive and grow in this well-known browsers world.

**Comment by yoavweiss** [comment]
The current thinking is that MyNewBrowser would be able add its own brand to the UA list, on top of e.g. the browser which engine it relies on.

So it could send out something like `"Firefox"; v="75", "MyNewBrowser"; v="34", "GreaseValueToPreventServersFromBlockingUnknownValues"; v=",;\""`

Closing, but feel free to reopen if your question was not answered.
