### ISSUE TITLE
Interface for getUserAgent missing Promise

### ISSUE THREAD

**Issue by cashpipeplusplus** [WICG/ua-client-hints#56]
In section 3, the interface says:

```js
interface mixin NavigatorUA {
  [SecureContext] NavigatorUAData getUserAgent();
};
```

In section 3.1, the processing model says that `getUserAgent()` returns a `Promise`.

I think the interface needs to be corrected to show a return type of `Promise<NavigatorUAData>` instead of just `NavigatorUAData`.

Thanks!

**Comment by amtunlimited** [comment]
Actually, it should be the other way around. The spec was recently changed so that getUserAgent's components gave promises instead of getUserAgent itself. Either way, pr needed.

**Comment by petemill** [comment]
If `getUserAgent` will no longer return be async, and will have child functions that are async, then does it need to be a function at all?

**Comment by yoavweiss** [comment]
Thanks for reporting! :)
This was obsoleted by #70. Closing
