### ISSUE TITLE
Language about Sec-CH-UA without opt-in is unclear about what is sent

### ISSUE THREAD

**Issue by othermaciej** [WICG/ua-client-hints#59]
> Unlike most Client Hints, the Sec-CH-UA header will be sent with all requests, whether or not the server opted-into receiving the header via an Accept-CH header. Prior to an opt-in, however, it will include only the user agent’s branding information, and the significant version number (both of which are fairly clearly sniffable by "examining the structure of other headers and by testing for the availability and semantics of the features introduced or modified between releases of a particular browser" [Janc2014]).

Does this mean that before opt-in, Sec-CH-UA will send different information than after opt-in? Or is this just describing what it will contain anyway, and comparing that to info available otherwise?

**Comment by yoavweiss** [comment]
This is obsoleted by #79, as `Sec-CH-UA` no longer requires an opt-in to send the significant version and `Sec-CH-UA-Full-Version` is the hint to get the full version. Closing.

**Comment by othermaciej** [comment]
Agreed that #79 addresses this issue. It's no longer confusing what's sent in `Sec-CH-UA`, since there is a separate `Sec-CH-UA-Full-Version` opt-in hint.
