### ISSUE TITLE
Do we need the `CH-` prefix?

### ISSUE THREAD

**Issue by mikewest** [WICG/ua-client-hints#6]
@yoavweiss: Where is Client Hints landing on this? I would much prefer `Sec-UA` if we've collectively decided that `CH-` is too ugly to live.

/cc @amtunlimited

**Comment by amtunlimited** [comment]
I wouldn't mind it being gone. Do any other client hints have the CH prefix?

**Comment by yoavweiss** [comment]
It's under active discussion at https://github.com/httpwg/http-extensions/pull/776
Current thinking is to include them as a convention.

**Comment by yoavweiss** [comment]
> Would that mean we should change the other client hints?

Yeah.

**Comment by yoavweiss** [comment]
After further [discussions](https://docs.google.com/document/d/1xLAcN2_5CPv4VzYSxpP_keSNs004sN9JE4tNwikHo84/edit) , we've decided to add `Sec-CH` prefixes: `Sec-` to avoid developers from changing to the headers and `CH-` as a convention that would enable servers to distinguish those content negotiation headers from others.
