### ISSUE TITLE
GREASE-like UA strings proposal might not work unless the MAY becomes a MUST

### ISSUE THREAD

**Issue by othermaciej** [WICG/ua-client-hints#60]
> History has shown us that there are real incentives for user agents to lie about their branding in order to thread the needle of sites' sniffing scripts, and prevent their users from being blocked by UA-based allow/block lists. .... Reseting expectations may help to prevent abuse of the UA string’s brand in the short term, but probably won’t help in the long run. ... User agents SHOULD model UA as a set, rather than a single entry. They then could encourage standardized processing of the UA string, by randomly including additional, intentionally incorrect, comma-separated entries with arbitrary ordering. 

This seems to be a good idea to maintain the viability of spoofing without totally hiding real branding. However, that's probably not the case if it's optional. A very popular browser could make itself harder to spoof by not following this.

**Comment by yoavweiss** [comment]
> This seems to be a good idea to maintain the viability of spoofing without totally hiding real branding. However, that's probably not the case if it's optional. A very popular browser could make itself harder to spoof by not following this.

I'm not sure I follow you. Can you outline why if a popular browser would not GREASE its UA string it would make it harder for other browsers to spoof it?

**Comment by othermaciej** [comment]
> I'm not sure I follow you. Can you outline why if a popular browser would not GREASE its UA string it would make it harder for other browsers to spoof it?

Because it could encourage websites to once again treat brand as a single entry, not a set, contrary to the intent of GREASE, as quoted in the OP.

I'm also kind of not sure why it needs to be optional. In general it's better for interop if exact behavior is specified; it's only good to use SHOULD or MAY instead of MUST if there is a good reason for some implementations to not follow the requirement. Is there such a need in this case?
