### ISSUE TITLE
Should Sec-UA-Arch define canonical names for popular architectures, or have a registry?

### ISSUE THREAD

**Issue by othermaciej** [WICG/ua-client-hints#61]
In current user agent strings, it's hard to make use of CPU architecture without reference to platform.

For example, popular browser UA strings refer to the x86-64 architecture as `x86_64` on Linux, `x64` on Windows, and `Intel` on Macs. To make it reasonable and useful to request `Sec-UA-Arch` by itself, there probably needs to be a consistent name for any given CPU architecture. To achieve this, the spec either needs to predefine some, or point to a registry.

You could just say that browsers ought to use whatever architecture name they send in the UA string, and clients just have to deal with multiple synonyms for the same architecture, but that misses a potential one-time opportunity for a useful cleanup.

(Note though that in #58 I suggest dropping this field, or allowing it to be blank or fictional, for browsers that chose not to expose the true CPU architecture at all.)

**Comment by mcatanzaro** [comment]
> For example, popular browser UA strings refer to the x86-64 architecture as `x86_64` on Linux, `x64` on Windows, and `Intel` on Macs.

Or on FreeBSD: amd64

**Comment by tresf** [comment]
> Or on FreeBSD: amd64

I've made this similar point here: https://github.com/WICG/ua-client-hints/pull/106/files#r428897514

**Comment by othermaciej** [comment]
Agreed that this is resolved by #106.
