### ISSUE TITLE
Pinpoint why user agents generally identify themselves to servers

### ISSUE THREAD

**Issue by jyasskin** [WICG/ua-client-hints#62]
Is it:
1. to help those servers know what browsers to test on and to fill in https://gs.statcounter.com/browser-market-share or
2. to allow servers to customize their output to the particular browser? 

Different answers seem to lead to different designs for `Sec-CH-UA`.

**Comment by yoavweiss** [comment]
![why not both](https://i.imgur.com/6rZ8g8R.jpg)

Those 2 cases are reasons for which browsers identify themselves:
* Market share statistics are important to browser vendors, and can encourage developers to test their sites in particular browsers.
* Differential serving can help browsers that support certain features to avoid downloading the polyfills for them.

What different designs did you have in mind?

**Comment by othermaciej** [comment]
There's also a reason 3 (or maybe 2a) which is to lock out some browsers entirely from some websites, either through a deny list, or an explicit deny list.

Reasons for this range from believing the site definite won't work in that browser, to merely not having tested and not wanting to devote the QA resources.

This is a bad reason which ideally should not be supported. But I'm not sure it's possible to enable (1) and (2) without also enabling (3).

**Comment by jyasskin** [comment]
Yep, @othermaciej's 2a is the key: Google's done a particularly visibly bad job of this lately, often telling users of any browser we didn't test with that they should use Chrome instead. 🤢 I think we can support (1) without supporting (2) using something like a differential privacy approach: telling the truth X% of the time, and a random lie (100-X)% of the time. If we want to support (2), GREASE can't have one browser claim to be another browser or omit the truth about which browser it is; GREASE is limited to adding a random non-browser to the list to ensure that servers are actually using a Structured-Headers parser.

If we want to support the good uses of (2) but not (2a), we might try to standardize the approach Edge and some others have used, of maintaining a list of servers who mis-use user-agent information. If we have a standard set of behaviors that get a domain onto and off of that list, maybe we could have everyone refuse to send any UA information to those domains...

**Comment by othermaciej** [comment]
A global list of domains that abuse user agent info is an interesting idea. A list like that created today, if managed rigorously, would include some top 100 domains (or subdomains thereof). If browsers stopped sending UA info to these sites entirely (even in the original User-Agent string), it would cause a lot of user disruption. Would browsers really be ok with that?

**Comment by yoavweiss** [comment]
> GREASE is limited to adding a random non-browser to the list to ensure that servers are actually using a Structured-Headers parser.

Re-ordering can also ensure that server parsers don't make assumptions regarding order.

> If we want to support the good uses of (2) but not (2a), we might try to standardize the approach Edge and some others have used, of maintaining a list of servers who mis-use user-agent information

As @othermaciej pointed out, such a list today will have significant compat challenges, so I wouldn't want to tie it to the initial UA-CH implementation and launch. At the same time, UA-CH would enable browsers to experiment with such an approach in the future.

Do you see any particular reason why we should standardize the list? There may be advantages to cross-browser coordination when taking action, but I'm not sure that requires standardization of the list or the concept.

**Comment by jyasskin** [comment]
+1 that re-ordering is also on the table, again to ensure servers are using a real Structured-Headers parser.

I also don't see a need to tie a UA-misuse list to the release of UA-CH, and it probably doesn't make sense to discuss it a lot on this issue. If UA-CH intends to allow servers to customize their output to the actual UA (which I weakly think it ought to), the document should say that, so we can shut down speculation that it might directly help with servers incorrectly blocking certain UAs.

Standardization is nice for both giving the affected people some amount of say in the policy, and for convincing all/enough browsers to actually follow the policy. It's not absolutely required.

**Comment by scottlow** [comment]
Thanks for opening this issue, @jyasskin! I think there's another question here that's fundamental to what we expose in `Sec-CH-UA` as well: **Who are we comfortable breaking or causing more work for?** Based on the current proposals I've seen so far, each would have a unique set of pros and cons for specific groups of stakeholders. Aligning on who we're okay breaking/causing more work for may be a useful exercise:

| Proposal | Helps | Potentially hurts |
| - | - | - |
| Exposing a per-browser identifier in `Sec-CH-UA` by default | Sites who are currently using the UA to obtain per-browser identifiers for various scenarios today | Browsers without large market share (see [Vivaldi's decision](https://vivaldi.com/press/releases/vivaldi-2-10-no-strings-attached/) to remove their UA token)  |
| Having browsers randomly lie about which one they are some small X% of the time | All browsers as it discourages the use of UA tokens for blocking sites | Users (as it will cause issues for legitimate browser-detection scenarios such as 'We noticed you just logged in with \<browser\>' security emails)
| Exposing a per-browser-engine identifier in `Sec-CH-UA` (or another CH) by default | Browsers (especially minority ones) based on well known engines today | Browsers based on new or unknown engines |
| Time-boxed UA tokens as proposed in #54 | All browsers as it strongly discourages the use of UA as an identifying mechanism for browsers | The long tail of the web (as it could break sites that don't update themselves to account for new tokens) |

It'd be great to get folks' thoughts on the above table/trade-offs as a starting point for driving consensus on what to expose. Personally, I'm leaning towards the latter two options for reasons covered in #52 and #54, but would love to get others' thoughts here as well!

**Comment by othermaciej** [comment]
> If UA-CH intends to allow servers to customize their output to the actual UA (which I weakly think it ought to), the document should say that, so we can shut down speculation that it might directly help with servers incorrectly blocking certain UAs.

In general, the spec should explain the intended use cases for all the client hints it defines. For some it's not obvious. Maybe I should file that as a separate issue.

**Comment by othermaciej** [comment]
I doubt a per-browser-engine identifier will help much, at least if there is also a browser identifier. Current UA strings have an engine identifier, and yet the browser identifier is often what's used. So I am not sure how this helps anyone, though it might be reasonable to include to avoid regressing.

**Comment by yoavweiss** [comment]
I believe the [use cases](https://github.com/WICG/ua-client-hints#use-cases) section now resolves this. @jyasskin - can you confirm?

**Comment by jyasskin** [comment]
Yep, fixed by #65.
