### ISSUE TITLE
Should browser version really be exposed in client hints?

### ISSUE THREAD

**Issue by mcatanzaro** [WICG/ua-client-hints#63]
Maintaining user agent quirks has become easier since WebKit froze its UA version string at 605.1.15. I hope that, if implementing the UA-CH spec, WebKit would choose to continue sending a fake, frozen version number, and not distinguish between ["significant version" and "full version."](https://wicg.github.io/ua-client-hints/#http-ua-hints) I believe WebKit has a strong interest in making it as difficult as possible for websites to use client hints to alter web content. (Currently the Safari major version number is still increasing, which is a shame. Websites and polyfills should rely on feature detection, not version numbers.)

The stated [rationale for including version information](https://wicg.github.io/ua-client-hints/#intro) is:

> Brand and version information (e.g. "Chrome 69") allows websites to work around known bugs in specific releases that aren’t otherwise detectable. For example, implementations of Content Security Policy have varied wildly between vendors, and it’s difficult to know what policy to send in an HTTP response without knowing what browser is responsible for its parsing and execution.

On the one hand, this seems like a strong argument for why websites would need to alter web content based on browser version. But it's easy to see that, if websites were to really alter CSP based on user agent string, the websites would break badly whenever a small browser sends a browser name and version that doesn't match what the website is expecting to see. It also largely contradicts the purpose of GREASEing the headers: the purpose of the GREASE is to discourage websites from altering web content based on the provided values, but the rationale for including version number only makes sense if websites can indeed rely on the provided values. That's a rather fundamental contradiction.

So I'd much rather expose as little information via client hints as possible. Web compatibility problems with CSP or other web platform features should be treated as bugs and fixed; we shouldn't expect websites to attempt to work around these by inspecting client hints. Including version numbers also creates an annoying game of catch-up for UAs trying to maintain quirks lists. It also encourages websites to blacklist old browser versions and display "unsupported browser" warnings or even entirely block access to the website on the basis of the provided version number, which significantly increases the effort required to maintain a quirks list. Not including this information would make it easier to maintain client hint quirks. (Quirks are inevitably going to be required, GREASE or no GREASE, for everything that's not Chromium.)

Although I'd rather not expose any version number information at all, if the spec does continue to expose versions, it should at least be limited to the "significant version," since full version is an obvious privacy risk and doesn't provide concrete benefit to websites.

CC @othermaciej

**Comment by mikesherov** [comment]
> So I'd much rather expose as little information via client hints as possible. Web compatibility problems with CSP or other web platform features should be treated as bugs and fixed; we shouldn't expect websites to attempt to work around these by inspecting client hints. 

The unfortunately reality is that bugs exist, and even if they get fixed quickly, "browser significant version" sniffing is the best tool we currently have to giving web developers and library authors a chance to patch over the platform while waiting for the browser fixes (and to support users who haven't upgraded off the broken version). 

> Although I'd rather not expose any version number information at all, if the spec does continue to expose versions, it should at least be limited to the "significant version," since full version is an obvious privacy risk and doesn't provide concrete benefit to websites.

Agreed. Significant version is coarse grained enough to not represent a true fingerprinting threat while still presenting a lifeline to library authors who need this information to patch undetectable web platform bugs.

**Comment by othermaciej** [comment]
In the Safari UA string, we have frozen everything besides browser marketing version (Version/13.0 or the like) and the OS marketing version. We don't bump any of the many other numbers in it.

Here's why we chose to unfreeze these:
- Web developers told us that they need the browser version for bug workarounds. Some bugs can't easily be feature detected, and doing the workaround unconditionally can be harmful in non-buggy versions. This seems kind of believable.
- Web developers told us they need the OS version so that, when offering downloads, they can offer the right one for the user's system (or only offer if compatible with that system).

There were secondary reasons like collecting user stats, which are not quite as compelling.

The bug workaround issue is the most concerning to me. I don't know of a good alternate way to solve it. I wish we could get rid of these versions entirely, this seems like the biggest obstacle.

**Comment by othermaciej** [comment]
In Safari, we'd probably expose the same granularity as is currently present in Version/ for both "significant" and "full". If this is ok for all browsers, then maybe there shouldn't be a difference.

**Comment by othermaciej** [comment]
(For us, "significant" would probably be more than one tumbler worth of version, but this probably wouldn't expose more than just the first number for other browsers.)

**Comment by yoavweiss** [comment]
I think this discussion should be split into two: "significant version" vs. "full version".

## Significant version use-cases

As @mikesherov and @othermaciej pointed out, bugs do exist and require content workarounds. Not all of them can be feature detected, and some of them also happen in historical versions that cannot be updated. A recent example is [same-site cookie incompatibilities](https://www.chromium.org/updates/same-site/incompatible-clients), but I'm sure there are many more.

Looking at the [use-cases](https://github.com/WICG/ua-client-hints#use-cases), it seems like I haven't explicitly spelled that out, and I probably should.

Beyond bugs, [differential serving](https://github.com/WICG/ua-client-hints#differential-serving-based-on-browser-features) of polyfills also seems like a critical use-case. While feature detection would be a better option for some polyfills, it's not always an option e.g. for JS transpilation, and it can be significantly slower than server-side logic.

The significant use-cases, combined with the fact that feature detection can typically reveal the UA version (even if in a slower manner), lead to the fact that the significant version is exposed by default, without requiring an opt-in.

## Full version use-cases

The full version has significantly less use-cases, and the main one I'm aware of is [vulnerability filtering](https://github.com/WICG/ua-client-hints#vulnerability-filtering), to enable security-sensitive sites to block users that run browsers with known vulnerabilities. As a specialized use-case that provides a high-entropy signal, this hint does require an opt-in.

I'm also comfortable with adding language that makes that exposure optional, to accomodate browsers that currently don't expose those version numbers (e.g. Safari).

**Comment by yoavweiss** [comment]
@mcatanzaro did I answer your questions? Can we close this?

**Comment by mcatanzaro** [comment]
Yes, as long as browsers have the option to expose only significant version, this is fine.

Note that we still might choose to lie about the significant version in the future (as with any hint, once it becomes necessary to lie for web compat, which is likely). But right now I think we have no plans to do that except when required for quirks.
