### ISSUE TITLE
Extending Sec-CH-UA-Model description to include device brand

### ISSUE THREAD

**Issue by ronancremin** [WICG/ua-client-hints#69]
Some use cases for the existing User-Agent header require details of the specific model making the request, as noted in the 20 February 2020 Client Hints [Draft Community Group Report](https://wicg.github.io/ua-client-hints/#intro) e.g. analytics and response tailoring.

The Sec-CH-UA-Model request header field is intended to solve this by giving a server "information about the device on which a given user agent is executing". However, as currently described (and named), the Sec-CH-UA-Model request header field doesn't currently suggest including anything about the brand, nor does the example given ("Pixel 2 XL").

The manufacturer component is important as there are many common model names across different brands e.g. at least 5 brands have an "X1" model and other model names such as A1, M1 and S1 are common also. 

Thus for this hint to fulfil its stated goal it would be useful to include language around including the device brand in the Sec-CH-UA-Model request header field's contents.

**Comment by yoshimo** [comment]
What do you need a brand and model number number for exactly?
Changing the general layout of a site can be done with screen size (also a fingerprint vector) or a simple "ismobile" boolean

**Comment by ronancremin** [comment]
It's not necessarily just layout that's being considered. Facebook and other websites change the entire HTML payload based on a performance classification scheme implemented on the server side.

But there are other use cases also e.g. working around device-specific issues.

**Comment by yoshimo** [comment]
What would  be a device specific but not browser specific issue? Usually an engine is used across multiple device models, even for mobile device specific browser forks like a Samsung browser

**Comment by ronancremin** [comment]
Performance. Regardless of browser, the underlying hardware performance varies greatly across the devices in use.

**Comment by yoshimo** [comment]
Do you happen to know a page that actually does behave differently between different models?
I can right now only imagine video codecs to be important and that can be solved without detailed info about a device and just "supported /preferred codecs"

**Comment by ronancremin** [comment]
I'm not sure exactly but my impression is that it's more or less site-wide. The problem they are solving is delivering a HTML/JS/CSS payload that can reasonably be handled by the device in question. A page that delivers a great experience on a Galaxy S20 might be too much for a S6 from 2015.

You can find out more in the following video, in the section delivered by Nate Schloss. https://dev.to/addyosmani/adaptive-loading-improving-web-performance-on-low-end-devices-1m69

**Comment by jonarnes** [comment]
Another example is mobile operator portals or services to configure OTA settings on devices.

**Comment by yoavweiss** [comment]
`Sec-CH-UA-Model` intends to maintain the same model information exposed in the `User-Agent` string today. Looking at e.g. [a sample of Android UA strings](https://deviceatlas.com/blog/list-of-user-agent-strings#android), some of them include the brand, but others don't. 

The spec currently defines the value as "information about the device", which seems to cover both options. I'm happy to make it more explicit to indicate that it may or may not include the device brand as well.

**Comment by yoavweiss** [comment]
Closing as I believe the question was answered, but let me know if more discussion is needed and I'll reopen

**Comment by ronancremin** [comment]
> The spec currently defines the value as "information about the device", which seems to cover both options. I'm happy to make it more explicit to indicate that it may or may not include the device brand as well.

The name of the header and its intent don't currently align that well, so making it more explicit that device brand might be included would be helpful guidance for implementors.

For background, while it is true to say that some devices include brand and some do not in the current UA string, the surrounding tokens UA string are typically sufficient to differentiate cases where there are model collisions. In the case of the Sec-CH-UA-Model header this ability is lost.

**Comment by abeyad** [comment]
The UA client hints, in their totality, can fully replace the current UA string and it's possible to reconstruct the full UA string from all of the UA client hints.  So for those cases where the brand isn't included in Sec-CH-UA-Model, but it can be inferred from other information in the UA string, then you could request the corresponding client hint that conveys the same information such that you could then infer the brand, no?

**Comment by ronancremin** [comment]
I think that this is certainly true for Chrome (as demonstrated in https://github.com/GoogleChromeLabs/uach-retrofill) but other browsers could make different decisions on the values to place in UA-CH headers.

It might be useful to suggest to browser implementers that, if moving to the UA-CH model, reconstruction of the previous UA string should be possible if all UA-CHs are made available to a server.
