### ISSUE TITLE
"UA" is being used for multiple things

### ISSUE THREAD

**Issue by yoavweiss** [WICG/ua-client-hints#73]
Feedback from @domenic on https://github.com/WICG/ua-client-hints/pull/70#discussion_r386533594 indicated that we use "UA" in various different ways (to indicate the overall collection of data collected through the API, as well as the brand+version in "uaSet".

Would be good to rename either the former or the latter, and align them with the exposed headers.

/cc @mikewest

**Comment by yoavweiss** [comment]
I think it may make sense to rename `uaList` to `brandList` to reduce confusion here

/cc @amtunlimited @morlovich

**Comment by domenic** [comment]
Maybe just "brands" even; a "list" suffix is a bit unusual.

**Comment by yoavweiss** [comment]
`brands` WFM
