### ISSUE TITLE
navigator.getUserAgent is missing on new Canary version

### ISSUE THREAD

**Issue by galmeiri** [WICG/ua-client-hints#83]
Hi,

The `navigator.getUserAgent()` method is not implemented in the new Canary version 82.0.4084.0. 
Is there any change in the planned implementation or the JS API usage?

**Comment by galmeiri** [comment]
Is this the way we need to implement the User Agent JS interface now?

```
// Browser brand and its version
navigator.userAgentData.uaList[0]

// Other properties
navigator.userAgentData.getHighEntropyValues(["platform", "platformVersion", "architecture", "model"]).then(res => console.log(res))

```

**Comment by galmeiri** [comment]
My bad, for some reason the chrome flags has been reset.

**Comment by yoavweiss** [comment]
Indeed. Following feedback, #70 has landed along with the corresponding [Chromium change](https://chromium-review.googlesource.com/c/chromium/src/+/2019369). Closing
