### ISSUE TITLE
Please add JS API examples

### ISSUE THREAD

**Issue by joeyparrish** [WICG/ua-client-hints#84]
The examples part of the spec only includes sample HTTP headers.  There are no examples in the doc for the JS API, and it's difficult to figure out how to use it from the WebIDL alone.

We have lots of UA version checks to ban or work around broken [MediaSource](https://www.w3.org/TR/media-source/) implementations in [Shaka Player](https://github.com/google/shaka-player).  I'd like to get a sense of how those will have to evolve once UA strings are frozen.

**Comment by yoavweiss** [comment]
Closed by #96
