### ISSUE TITLE
What Validation rules are set for the ua-client-hints string fields

### ISSUE THREAD

**Issue by ayumi-cloud** [WICG/ua-client-hints#87]
We know the following:

`Sec-CH-UA` - uses [5.2. GREASE-like UA Strings](https://wicg.github.io/ua-client-hints/#grease)

`Sec-CH-UA-Platform` - string

`Sec-CH-UA-Arch` - string

`Sec-CH-UA-Model` - string

`Sec-CH-UA-Mobile` - boolean

Our question is with regards to the strings and what characters are blacklisted and whitelisted to prevent hackers trying to send Malicious strings.

Also some Asian search engines for example in Korea and China use funny characters in their user-agents like the character `~` 

Would be grateful to get a rough idea as we will be saving the results into a database and want to add validation rules to protect the database before saving the data.

Thanks.

p.s. Please add a bit more info in the spec with regards to this.

[edit] **Forgot to mention we are hoping to create a regex solution.**

**Comment by yoavweiss** [comment]
Defining what the values of the strings would be for the different user agents is beyond the scope of this proposal. Beyond that, if we were to define strict rules, that would make it easer for hackers to comply with them, wouldn't it?

**Comment by ayumi-cloud** [comment]
@yoavweiss 

> Defining what the values of the strings would be for the different user agents is beyond the scope of this proposal. 

Surely this proposal should include some basic rules?

1. For example, a character limit to stop hackers doing a DDOS attack by injecting really long strings.

2. Are the `Sec-CH-*` meant to be written in **English only** or can foreign languages be written like Chinese, Korean or Arabic etc. using non-latin set characters and/or ascii.

> Beyond that, if we were to define strict rules, that would make it easer for hackers to comply with them, wouldn't it?

3. We have done a basic https://www.php.net/manual/en/function.htmlentities.php to protect the values. This proposal should at least mention escaping things!

**Comment by yoavweiss** [comment]
Client Hints headers in general and UA-CH in particular are not special in those respects.

This proposal relies on [Structured Headers definition of string](https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-17#section-3.3.3) to answer those questions:
* "Strings are zero or more printable ASCII [RFC0020] characters (i.e., the range %x20 to %x7E).  Note that this excludes tabs, newlines, carriage returns, etc."
* "Parsers MUST support Strings (after any decoding) with at least 1024 characters."
* "Strings are delimited with double quotes, using a backslash ("\") to escape double quotes and backslashes"

**Comment by ayumi-cloud** [comment]
@yoavweiss thanks for the info 👍

**Comment by yoavweiss** [comment]
Can we close this?
