### ISSUE TITLE
"forbid access to these headers from JavaScript" is unclear

### ISSUE THREAD

**Issue by zhaoz** [WICG/ua-client-hints#98]
https://wicg.github.io/ua-client-hints/#sec-ch has this statement: "it seems reasonable to forbid access to these headers from JavaScript"

This should be clarified for two reasons:
1. "seems reasonable" does not give definitive guidance on the current state of access control.
2. This reads like JavaScript is not allowed to *read* the client hints. From conversations, it seems like JavaScript forbidden from *writting* client hints.

**Comment by yoavweiss** [comment]
Thanks for reporting. I'll clarify
